function isDevelopmentServer(){var result=false,hosts=["localhost","127.0.0.1","aspenmobile.myfollett.com","aspenmobilecl.myfollett.com"],domain=window.location.hostname,i;if(window.location!==null)if(window.location.hostname!==null)for(i=0;i<hosts.length;i++)if(domain.indexOf(hosts[i])>=0){result=true;break}return result}function isAnalyticsTrackingEnabled(){return typeof trackAnalytics!=="undefined"&&trackAnalytics===true}
try{if(isAnalyticsTrackingEnabled()){(function(i,s,o,g,r,a,m){i["GoogleAnalyticsObject"]=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date;a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,"script","//www.google-analytics.com/analytics.js","ga");if(isDevelopmentServer())ga("create","UA-39868263-14",{"cookieDomain":"none"});else ga("create","UA-39868263-15",{"sampleRate":10});if(typeof analyticUserRole!==
"undefined")ga("set","dimension1",analyticUserRole);if(typeof analyticUserView!=="undefined")ga("set","dimension2",analyticUserView);if(typeof aspenVersion!=="undefined")ga("set","dimension3",aspenVersion);if(typeof districtName!=="undefined")ga("set","dimension4",districtName);ga("send","pageview")}}catch(E){}
function sendEvent(action,label,value){var category="Google Drive API";if(isAnalyticsTrackingEnabled())if(value!==undefined)ga("send","event",category,action,label,value);else ga("send","event",category,action,label)}
function sendEventWithCallback(action,label,value,callbackSucess,callbackFail){var category="Google Drive API";if(isAnalyticsTrackingEnabled())ga("send","event",{"eventCategory":category,"eventAction":action,"eventLabel":label,"eventValue":value,"hitCallback":function(){if(callbackSucess!==undefined)callbackSucess()},"hitCallbackFail":function(){if(callbackFail!==undefined)callbackFail()}});else if(callbackSucess!==undefined)callbackSucess()}
function appendMessageToLabel(label,message){return label+" { "+message+" }"}
function getGDALabel(){var LABEL={};LABEL.LABEL_GOOGLE_DRIVE_ACCESS_FROM_ASSIGNMENT_ATTACHMENT="ASSIGNMENT ATTACHMENT";LABEL.LABEL_GOOGLE_DRIVE_ACCESS_FROM_ASSIGNMENT_SUBMISSION="ASSIGNMENT SUBMISSION";LABEL.LABEL_GOOGLE_DRIVE_ACCESS_FROM_RESOURCES="RESOURCES";LABEL.LABEL_GOOGLE_DRIVE_ACCESS_FROM_DOC_LIST_PREVIEW="DOCUMENT LIST PREVIEW";LABEL.LABEL_GOOGLE_DRIVE_ACCESS_ALLOW="ALLOW";LABEL.LABEL_GOOGLE_DRIVE_ACCESS_CANCEL="CANCEL";LABEL.LABEL_GOOGLE_DRIVE_ACCESS_REVOKE="REVOKE";return LABEL}
function getRange(num){num=num/100;num=Math.floor(num);return""+num*100+"-"+((num+1)*100-1)}
function getGDAAction(){var ACTION={};ACTION.EVENT_GOOGLE_DRIVE_ACCESS_CONSENT_SCREEN_ACCEPT="ACCESS-CONSENT_SCREEN_ACCEPT";ACTION.EVENT_GOOGLE_DRIVE_ACCESS_CONSENT_SCREEN_CANCEL="ACCESS-CONSENT_SCREEN_CANCEL";ACTION.EVENT_GOOGLE_DRIVE_ACCESS_REVOKE="ACCESS-REVOKE";ACTION.EVENT_GOOGLE_DRIVE_ACCESS_FAILED="ACCESS-FAILED";ACTION.EVENT_GOOGLE_DRIVE_USE_DOC_LIST_RETRIEVED="USAGE-DOC_LIST_RETRIEVED";ACTION.EVENT_GOOGLE_DRIVE_USE_DOC_OPEN_REQUEST="USAGE-DOC_OPEN_REQUEST";ACTION.EVENT_GOOGLE_DRIVE_USE_DOC_OPEN_REQUEST_FAILED=
"USAGE-DOC_OPEN_REQUEST_FAILED";return ACTION};