var Aspen={};var sessionId="000000";var schedulingProcessRefreshEvent=false;var sessionTimeout=0;var tableLockTimeout=0;var timeoutDuration=0;var lastUserEvent=0;var idSessionTimeout=0;var allowSubmit=true;var submitted=false;var popup=null;var popupSaved=null;var popupBlocked=false;if(!x2opener){var x2opener=this.opener;if(this.name=="root_aspen_window")x2opener=null}
parseUri.options={strictMode:false,key:["source","protocol","authority","userInfo","user","password","host","port","relative","path","directory","file","query","anchor"],q:{name:"queryKey",parser:/(?:^|&)([^&=]*)=?([^&]*)/g},parser:{strict:/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/,loose:/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/}};
var canPost=new Array;var reqInProgress=false;
$(function(){$("#left-arrow-container").mousedown(function(e){startScrollingTopTabs("-",e)}).mouseup(stopScrollingTopTabs).mouseout(stopScrollingTopTabs);$("#right-arrow-container").mousedown(function(e){startScrollingTopTabs("+",e)}).mouseup(stopScrollingTopTabs).mouseout(stopScrollingTopTabs);$("#sideMenuArrowToUp").mousedown(function(e){startScrollingSideTabs("-",e)}).mouseup(stopScrollingSideTabs).mouseout(stopScrollingSideTabs);$("#sideMenuArrowToDown").mousedown(function(e){startScrollingSideTabs("+",e)}).mouseup(stopScrollingSideTabs).mouseout(stopScrollingSideTabs);
setTimeout(function(){resizeSideScrolling();resizeTopTabsScrolling();resizeSideArrows()},200);$(window).resize(function(){resizeTopTabsScrolling();resizeSideScrolling();setTimeout(function(){resizeTopTabsScrollingAfterWindowResized()},250)});$("#pageMenuContainer").click(function(){setTimeout(function(){resizeTopTabsScrolling();resizeSideScrolling();resizeSideArrows()},200)});var hWin=getParentX2Window();hWin.lastUserEvent=0;$(document).keydown(function(){var hWin=getParentX2Window();hWin.lastUserEvent=
(new Date).getTime()});$(document).click(function(){var hWin=getParentX2Window();hWin.lastUserEvent=(new Date).getTime()});EmbeddedPopup.popupManager=new EmbeddedPopup;trackFormFocus();includeReaderImprovements("js/reader-accessibility.js")});var EVENT={};EVENT.repositoryItemDropped="repositoryItemDropped";EVENT.repositoryItemTreeCopy="repositoryItemTreeCopy";EVENT.refreshAllRepositoryTrees="refreshAllRepositoryTrees";EVENT.coverIframe="coverIframe";EVENT.repositoryItemRemoved="repositoryItemRemoved";
EVENT.lessonPlannerRepositoryItemRemoved="lessonPlannerRepositoryItemRemoved";EVENT.changePlannerMode="changePlannerMode";EVENT.contentItemDeleteClick="contentItemDeleteClick";function addBodyClass(newClass){$(document.body).addClass(newClass)}function addToDelimitedList(list,value,delimiter){var separation=",";if(delimiter!=null)separation=delimiter;if(list.length>0)list+=separation;list+=value;return list}
function addPickListDynamicFilters(url){var urlParams=parseUrlParams(url);var filters=urlParams["filters"];if(filters&&(filters.indexOf("!input!")>-1||filters.indexOf("!detail!")>-1)){var filterRegex=/[^!(,]+![^!]+![^!]+!(input|detail)!([^!(),]+)/g;var dynamicFilters=[];var matchResult;while((matchResult=filterRegex.exec(filters))!==null){var fieldName=matchResult[2];var value=null;var propertyValue=$(":input[name='propertyValue("+fieldName+")'], :input[name='parametersAsStrings("+fieldName+")']");
if(propertyValue.length)value=propertyValue.val();if(value)dynamicFilters.push(fieldName+"!"+value)}if(dynamicFilters)url+="&dynamicFilters="+dynamicFilters.join(",")}return url}function bakeCookie(name,value,path,days){var expires;if(days){var date=new Date;date.setTime(date.getTime()+days*24*60*60*1E3);expires="expires="+date.toGMTString()+";"}else expires="expires=;";document.cookie=name+"="+value+"; "+expires+" path="+path}
function catchTab(item,e){if(navigator.userAgent.match("Gecko"))c=e.which;else c=e.keyCode;if(c==9){replaceSelection(item,"  ");setTimeout("document.getElementById('"+item.id+"').focus();",0);return false}}function checkDelimitedList(list,value){var found=false;var existingValues=list.split(",");for(var i=0;i<existingValues.length;i++)if(value==existingValues[i]){found=true;break}return found}
function children(object){var children;if(object.getAttribute("children"))children=object.children;else{children=new Array;var index=0;var childNodes=object.childNodes;for(var i=0;i<childNodes.length;i++)if(childNodes[i].nodeType==1){children[index]=childNodes[i];index++}}return children}function clearInputElementByName(elementName){$("input[name='"+escapeJQuery(elementName)+"']").val("")}
function confirmRemoveWorkflow(event,form,parameter){if(confirm(grabResource("message.conduct.removeWorkflow")))doParamSubmit(event,form,parameter)}function decodeParameter(value){value=decodeURIComponent(value);value=value.replace(/&amp;/g,"&");return value}function destroyWizard(){makeAsynchronousXmlRequest("destroyWizard.do",null,null,null,null)}
function disableAllElements(element,disable){try{element.disabled=disable}catch(E){}if(element.childNodes&&element.childNodes.length>0)for(var i=0;i<element.childNodes.length;i++)disableAllElements(element.childNodes[i],disable)}function disableForm(form){var elements=form.elements;for(var i=0;i<elements.length;i++)if(elements[i].type=="button"&&elements[i].name!="closeButton"){elements[i].readOnly=true;elements[i].disabled=true}}
function doCopy(nameProperty,relationships,uniqueProperties,directValuesToSet){var url="copy.do?nameProperty="+nameProperty+"&relationships="+relationships+"&uniqueProperties="+uniqueProperties+"&definedProperties="+directValuesToSet;doPopup(url,"350","150")}
function doCopyTranscriptColumnDefinition(nameProperty,relationships,uniqueProperties,directValuesToSet){var url="copyTranscriptColumnDefinition.do?nameProperty="+nameProperty+"&relationships="+relationships+"&uniqueProperties="+uniqueProperties+"&definedProperties="+directValuesToSet;doPopup(url,"350","150")}
function doCopyAction(action,nameProperty,relationships,uniqueProperties,directValuesToSet,applySystemValues){if(!action.endsWith(".do"))action+=".do";var url=action+"?nameProperty="+nameProperty+"&relationships="+relationships+"&uniqueProperties="+uniqueProperties+"&definedProperties="+directValuesToSet+"&applySystemValues="+applySystemValues;doPopup(url,"350","150")}
function doNamedPopup(url,width,height,windowName,extraOptions,xOffset,yOffset,keepOpen,align){windowName=(windowName||"").replace(/\s/g,"_");var windowWidth=isMozillaDerivative()?window.outerWidth:document.body.clientWidth;var windowHeight=isMozillaDerivative()?window.outerHeight:document.body.clientHeight;var windowX=isMozillaDerivative()?window.screenX:window.screenLeft;var windowY=isMozillaDerivative()?window.screenY:window.screenTop;if(xOffset)windowX+=xOffset;if(yOffset)windowY+=yOffset;var left;
if(align=="left")left=0;else if(align=="right")left=screen.availWidth-width-25;else{left=(windowWidth-width)/2;left+=windowX}var top=windowY+(windowHeight-height)/2;if(typeof extraOptions=="undefined")extraOptions="";var standardOptions="scrollbars=1,resizable=1,menubar=1,location=0";var windowOptions=(extraOptions==""?standardOptions:extraOptions)+",width="+width+",height="+height+",left="+left+",top="+top;var paramChar="?";if(url.indexOf(paramChar)!=-1)paramChar="&";var form=document.forms[0];if(form!=
null&&form.elements["deploymentId"]!=null&&form.elements["deploymentId"].value!=null)url+=paramChar+"deploymentId="+form.elements["deploymentId"].value;popup=window.open(rewriteUrl(url),windowName,windowOptions);popupBlocked=!popup||popup.closed||typeof popup.closed=="undefined";if(popup!=null)try{popup.focus()}catch(e){}if(keepOpen==true){popupSaved=popup;popup=null}}function doNothing(){}function doParamSubmit(event,form,parameter){form.userParam.value=parameter;doSubmit(event,form)}
function doParamSubmitByName(event,formName,parameter){var form=document.forms[formName];if(form==null)form=document.forms[0];doParamSubmit(event,form,parameter)}function doParamTargetSubmit(event,form,parameter,target){form.action=form.action+"#"+target;doParamSubmit(event,form,parameter)}
function doParentParamSubmit(event,parentFormName,parameter){var parentWin=findParent();if(parentWin!=null){if(parentFormName!=null)parentForm=parentWin.document.forms[parentFormName];else{parentForm=parentWin.document.forms[0];if(parentForm.primaryForm&&parentForm.primaryForm.value=="false")for(var i=0;i<parentWin.document.forms.length;i++){parentForm=parentWin.document.forms[i];if(parentForm.primaryForm&&parentForm.primaryForm.value=="true")break}}parentWin.doParamSubmit(event,parentForm,parameter)}}
function doParentRedirect(url){var parentWin=findParent();if(parentWin!=null){parentWin.name="parentWindow";parentWin.open(rewriteUrl(url),parentWin.name)}}
function doParentSubmit(event,parentFormName){var parentWin=findParent();if(parentWin!=null){if(parentFormName!=null)parentForm=parentWin.document.forms[parentFormName];else{parentForm=parentWin.document.forms[0];if(parentForm.primaryForm&&parentForm.primaryForm.value=="false")for(var i=0;i<parentWin.document.forms.length;i++){parentForm=parentWin.document.forms[i];if(parentForm.primaryForm&&parentForm.primaryForm.value=="true")break}}parentWin.doSubmit(event,parentForm)}}
function doPickList(url,width,height,windowName){if(width==null)width=600;if(height==null)height=500;if(windowName==null)windowName="pickList";saveFormFocusFromUrl(url);doNamedPopup(addPickListDynamicFilters(url),width,height,windowName,"")}
function doPickListSearch(url,formName,elementName,searchParameter,width,height,extraElement,extraParameter){var form=document.forms[formName];if(form==null)form=document.forms[0];var searchValue=form.elements[elementName].value;url=url+"&"+searchParameter+"="+encodeURIComponent(searchValue);if(extraElement){var extraValue=document.forms[formName].elements[extraElement].value;url=url+"&"+extraParameter+"="+encodeURIComponent(extraValue)}if(elementName)saveFormFocus(elementName);doPickList(url,width,
height)}function doPopup(url,width,height){doNamedPopup(url,width,height,"remote","")}function doPost(url,parameters,callback,async){if(typeof async=="undefined")var async=true;$.ajax({type:"POST",url:rewriteUrl(url),data:parameters,success:function(data){resetSessionTimeout();if(data.hasOwnProperty("success")&&!data.success)showAjaxErrorMessage(data);else if(callback)callback(data)},async:async})}function doSelfRedirect(url){this.name="mainWindow";this.open(rewriteUrl(url),this.name)}
function doSubmitRefreshEvent(event,form){schedulingProcessRefreshEvent=true;doSubmit(event,form)}
function doSubmit(event,form){try{if(allowSubmit==true&&form!=null&&(submitted==false||isInternetExplorer6()||isInternetExplorer7())){submitted=true;form.userEvent.value=event;if(form.userEvent.length)form.userEvent[0].value=event;disableForm(form);if(this.populateForm)populateForm();saveScrollCoordinates();if(this.beforeFormSubmit)beforeFormSubmit();try{form.submit()}catch(e){submitted=false}}if(allowSubmit==false)alert(grabResource("message.pageLoading"))}catch(e){submitted=false;throw e;}}
function doSubmitByName(event,formName){var form=document.forms[formName];if(form==null)form=document.forms[0];doSubmit(event,form)}function doParamSubmitByName(event,formName,parameter){var form=document.forms[formName];if(form==null)form=document.forms[0];doParamSubmit(event,form,parameter)}function doTargetSubmit(event,form,target){form.action=form.action+"#"+target;doSubmit(event,form)}
function doValueSubmit(event,formElementName,value){var form=document.forms[0];if(form.elements[formElementName]!=null)form.elements[formElementName].value=value;doSubmit(event,form)}function doWizard(url,width,height){if(!width)width="660";if(!height)height="500";doNamedPopup(url,width,height,"wizard","scrollbars=1,resizable=1,menubar=0,location=0")}function eatCookie(name,path){bakeCookie(name,"",path,-1)}
function elementAddListener(element,type,listener,useCapture){if(element!=null)if(element.addEventListener!=null&&!isInternetExplorer()){if(useCapture==null)useCapture=false;element.addEventListener(type,listener,useCapture)}else $(element).on(type,listener)}
function elementChainEvent(firstFunc,secondFunc){if(firstFunc&&secondFunc)return function(){firstFunc.call(this,arguments);secondFunc.call(this,arguments)};else if(firstFunc)return firstFunc;else if(secondFunc)return secondFunc;else return null}
function elementFireEvent(element,type){if(element.dispatchEvent!=null&&document.createEvent!=null)try{var eventObject=document.createEvent("HTMLEvents");eventObject.initEvent(type,true,false);element.dispatchEvent(eventObject)}catch(e){$(element).trigger(type)}else $(element).trigger(type)}function elementRemoveListener(element,type,listener){if(element.removeEventListener&&!isInternetExplorer())element.removeEventListener(type,listener,false);else $(element).unbind("on"+type,listener)}
function enableUserAccounts(){if(confirm(grabResource("message.truncate.warning")))makeSynchronousTextRequest("enableUserAccounts.do","enableUserAccountsSuccess","enableUserAccountsError()")}function enableUserAccountsSuccess(text){alert(text)}function enableUserAccountsError(){alert("Communication Error")}
function encodeParameter(value){value=escape(value);value=value.replace(/\//g,"%2F");value=value.replace(/\?/g,"%3F");value=value.replace(/=/g,"%3D");value=value.replace(/&/g,"%26");value=value.replace(/@/g,"%40");value=value.replace(/,/g,"%2C");return value}function escapeJQuery(str){return str.replace(/([#;&,\.\+\*~':"!\^\$\[\]\(\)=>|\/\\])/g,"\\$&")}
function fadeOpacity(id,opacStart,opacEnd,millisec){var speed=Math.round(millisec/100);var timer=0;var i=0;if(opacStart>opacEnd)for(i=opacStart;i>=opacEnd;i--)setTimeout("setOpacity("+i+",'"+id+"');",timer++*speed);else if(opacStart<opacEnd)for(i=opacStart;i<=opacEnd;i++)setTimeout("setOpacity("+i+",'"+id+"');",timer++*speed)}function findParent(){var parentWin=null;if(x2opener!=null)parentWin=x2opener;else if(window.parent!=null)parentWin=window.parent;return parentWin}
function findPositionX(obj){return $(obj).offset().left}function findPositionY(obj){return $(obj).offset().top}function forceElementToArray(object){var forcedArray;if(object.length)forcedArray=object;else{forcedArray=new Array(1);forcedArray[0]=object}return forcedArray}
function getElementByIdSafe(id){var element=document.getElementById(id);if(element!=null)if(id!=element.id){element=null;var elements=document.all;if(elements!=null)for(var i=elements.length-1;i>=0;i--)if(elements[i].id==id){element=elements[i];break}}return element}
function getParentX2Window(){var parentWin=x2opener;try{if(parentWin==null||typeof parentWin=="undefined"||typeof parentWin.getParentX2Window=="undefined"||typeof parentWin.getParentX2Window=="unknown")parentWin=this}catch(err){parentWin=this}return parentWin}
function getRequestObject(){var requestObject=false;if(window.XMLHttpRequest)requestObject=new XMLHttpRequest;else if(window.ActiveXObject)requestObject=new ActiveXObject("Microsoft.XMLHTTP");if(!requestObject)alert("***** UNSUPPORTED BROWSER: Cannot create an XMLHTTP object.");return requestObject}function getRootX2Window(current){if(!current)current=this;var root=current.getParentX2Window();if(current!=root)root=getRootX2Window(root);return root}
function getScrollbarWidth(){var noScrollWidth=0;var scrollWidth=0;var outerDiv=document.createElement("div");outerDiv.style.position="absolute";outerDiv.style.top="-1000px";outerDiv.style.left="-1000px";outerDiv.style.width="100px";outerDiv.style.height="50px";outerDiv.style.overflow="hidden";var innerDiv=document.createElement("div");innerDiv.style.width="100%";innerDiv.style.height="200px";outerDiv.appendChild(innerDiv);document.body.appendChild(outerDiv);noScrollWidth=innerDiv.offsetWidth;outerDiv.style.overflow=
"auto";if(noScrollWidth-innerDiv.offsetWidth==0)outerDiv.style.overflow="scroll";scrollWidth=innerDiv.offsetWidth;var SCROLLBAR_WIDTH=noScrollWidth-scrollWidth;document.body.removeChild(document.body.lastChild);return SCROLLBAR_WIDTH}
function getScrollCoordinates(){var x;var y;if(self.pageYOffset){x=self.pageXOffset;y=self.pageYOffset}else if(document.documentElement&&document.documentElement.scrollTop){x=document.documentElement.scrollLeft;y=document.documentElement.scrollTop}else if(document.body){x=document.body.scrollLeft;y=document.body.scrollTop}return new Array(x,y)}function getTextContent(element){return element.textContent||element.text}
function getTimeoutMessage(){var html='<table><tr><td style="font-size:13px;">'+sessionTimeoutMessage1+"<br><br>"+sessionTimeoutMessage2+'</td><td width=25% style="text-align:center; vertical-align:center">'+'<div id="timeoutClock" class="timerCount">60'+getTimerAnimation(60,5)+"</div></td></tr></table>";return html}
function getTableLockTimeoutMessage(countDownTime){tableLockTimeout=(new Date).getTime()+6E4;if(countDownTime!=null)tableLockTimeout=(new Date).getTime()+countDownTime;var parentWindow=getParentX2Window();clearTimeout(parentWindow.tableLockTimeoutHandle);parentWindow.tableLockTimeoutHandle=null;var html='<table><tr><td style="font-size:13px;">'+tableLockTimeoutMessage1+"<br><br>"+tableLockTimeoutMessage2+'</td><td width=25% style="text-align:center; vertical-align:center">'+'<div id="tableLockTimeoutClock" class="timerCount">60'+
getTimerAnimation(60,5)+"</div></td></tr></table>";return html}function getTimerAnimation(index,columns){var html='<table class="timerAnimation">';for(i=0;i<columns;i++){cellStyle="timerAnimationCell1";if(index%columns==i)cellStyle="timerAnimationCell2";html=html+'<td class="'+cellStyle+'">&nbsp;</td>'}html=html+"</tr></table>";return html}function getTopWindowHandle(){var hWin=this;while(hWin.popup!=null&&!hWin.popup.closed)hWin=hWin.popup;return hWin}
function getWindowHeight(){var y=0;if(self.innerHeight)y=self.innerHeight;else if(document.documentElement&&document.documentElement.clientHeight)y=document.documentElement.clientHeight;else if(document.body)y=document.body.clientHeight;return y}function getWindowWidth(){var x=0;if(self.innerWidth)x=self.innerWidth;else if(document.documentElement&&document.documentElement.clientWidth)x=document.documentElement.clientWidth;else if(document.body)x=document.body.clientWidth;return x}
function goPreLoad(preLoadUrl,goUrl){var callback=null;if(arguments.length>2){var args=Array.prototype.slice.call(arguments);args.splice(0,1);callback=args}preLoadUrl=rewriteUrl(preLoadUrl);$.ajax({type:"GET",url:preLoadUrl,async:false,success:function(){if(callback!=null)goPreLoad.apply(this,callback);else if(goUrl!=null)window.location=goUrl},error:function(){if($("#sra-status").length)$("#sra-status").text("Communication failure");else window.location=preLoadUrl},cache:false})}
function hideLoadingCover(){$("#loadingCover").hide()}
function includeCommonStylesheet(media,relativePath){var browserSuffix="";if(isInternetExplorer()||isOpera())browserSuffix="ie";else browserSuffix="mo";if(media==null)media="screen";if(relativePath==null){document.write('<link rel=StyleSheet href="css/common-'+browserSuffix+'.css" type="text/css" media="'+media+'">');document.write('<link rel=StyleSheet href="css/colorPatternPicker.css" type="text/css" />')}else{document.write('<link rel=StyleSheet href="'+relativePath+"css/common-"+browserSuffix+
'.css" type="text/css" media="'+media+'">');document.write('<link rel=StyleSheet href="'+relativePath+'css/colorPatternPicker.css" type="text/css" />')}}function includePrintableStylesheet(){includeCommonStylesheet();includeCommonStylesheet("print");document.write('<link rel=StyleSheet href="css/printable.css" type="text/css" media="screen">');document.write('<link rel=StyleSheet href="css/printable.css" type="text/css" media="print">')}
function includeStylesheet(context){includeCommonStylesheet();document.write('<link rel=StyleSheet href="css/'+context+'.css" type="text/css" media="screen">')}function indexOfArray(array,value){var len=array.length;for(var from=0;from<len;from++)if(from in array&&array[from]===value)return from;return-1}function isCamino(){return navigator.userAgent.indexOf("Camino")!=-1}function isChrome(){return navigator.userAgent.indexOf("Chrome")!=-1}
function isFirefox(){return navigator.userAgent.indexOf("Firefox")!=-1}function isFirefox64Bit(){return navigator.userAgent.indexOf("Namoroka")!=-1}function isInternetExplorer(){return(navigator.appName=="Microsoft Internet Explorer"||navigator.appName=="Netscape"&&(new RegExp("Trident/.*rv:([0-9]{1,}[.0-9]{0,})")).exec(navigator.userAgent)!=null)&&!isOpera()}function isInternetExplorerNotVerTen(){var isIE10=false;return isInternetExplorer()&&!isIE10}
function isInternetExplorer6(){var isIe6=false;return isIe6}function isInternetExplorer7(){var isIe7=false;return isIe7}function isInternetExplorer8(){var isIe8=false;return isIe8}function isInternetExplorer9(){var isIe9=false;return isIe9}function isInternetExplorerModern(){var isIeModern=false;return isIeModern}function isInternetExplorer64Bit(){return navigator.appName=="Microsoft Internet Explorer"&&!isOpera()&&navigator.appVersion.indexOf("x64")!=-1}
function isMozilla(){return navigator.appName=="Netscape"&&!isCamino()&&!isFirefox()&&!isNetscape()&&!isSafari()&&!isChrome()}function isMozillaDerivative(){return navigator.appName=="Netscape"}function isMacintosh(){return navigator.appVersion.indexOf("Macintosh")!=-1}function isNetscape(){return navigator.userAgent.indexOf("Netscape")!=-1}function isOpera(){return navigator.userAgent.indexOf("Opera")!=-1}function isSafari(){return navigator.userAgent.indexOf("Safari")!=-1&&!isChrome()}
function isWindows(){return navigator.appVersion.indexOf("Windows")!=-1}function isX11(){return navigator.appVersion.indexOf("X11")!=-1}
function limitText(theEvent,theField,maxLength){theEvent=theEvent||window.event;if(theEvent){var content=theField.getTextOnlyContent?theField.getTextOnlyContent():theField.value;var keyCode=theEvent.charCode||theEvent.keyCode;if(maxLength>0&&content.length>maxLength){var thePattern=/\s/g;if(String.fromCharCode(keyCode).match(thePattern)||keyCode>46||theEvent.altKey||theEvent.shiftKey||keyCode==16||keyCode==18){trimField(theField,maxLength,false);if(theEvent.preventDefault)theEvent.preventDefault();
else theEvent.returnValue=false;return false}}if(theEvent.ctrlKey&&theEvent.keyCode==86||theEvent.shiftKey&&theEvent.keyCode==45)trimField(theField,maxLength,false)}return true}function logTime(s,time){var date=new Date(time);console.log(s+": "+date.toLocaleTimeString()+" "+date.getMilliseconds())}
function makeAsynchronousTextRequest(url,successFunction,failureFunction){var requestObject=getRequestObject();if(requestObject){requestObject.onreadystatechange=function(){if(requestObject.readyState==4)if(requestObject.status==200)if(typeof successFunction=="string"){var brIndex=successFunction.indexOf("(");if(brIndex!=-1)successFunction=successFunction.substring(0,brIndex);eval(successFunction+"(requestObject.responseText);")}else successFunction(requestObject.responseText);else eval(failureFunction)};
requestObject.open("GET",rewriteUrl(url),true);requestObject.send(null)}}
function makeAsynchronousXmlRequest(url,successFunction,failureFunction,postInputParam,postInput){var requestObject=getRequestObject();if(requestObject){requestObject.onreadystatechange=function(){if(requestObject.readyState==4)if(requestObject.status==200){var evalFunct=successFunction+"(requestObject.responseXML);";if(successFunction.indexOf("(")>-1)evalFunct=successFunction.substring(0,successFunction.length-1)+",requestObject.responseXML);";eval(evalFunct)}else eval(failureFunction)};if(postInput){url=
setCSRFProtection(url);requestObject.open("POST",rewriteUrl(url),true);requestObject.setRequestHeader("Content-Type","application/x-www-form-urlencoded");requestObject.send(postInputParam+"="+encodeURIComponent(postInput))}else{requestObject.open("GET",rewriteUrl(url),true);requestObject.send(null)}}}
function makeSynchronousTextRequest(url,successFunction,failureFunction){var requestObject=getRequestObject();if(requestObject){requestObject.open("GET",rewriteUrl(url),false);requestObject.send(null);if(requestObject.status==200)eval(successFunction+"(requestObject.responseText);");else eval(failureFunction)}}
function makeSynchronousXmlRequest(url,successFunction,failureFunction,postInputParam,postInput){var requestObject=getRequestObject();if(requestObject){if(postInput){url=setCSRFProtection(url);requestObject.open("POST",rewriteUrl(url),false);requestObject.setRequestHeader("Content-Type","application/x-www-form-urlencoded");requestObject.send(postInputParam+"="+encodeURIComponent(postInput))}else{requestObject.open("GET",rewriteUrl(url),false);requestObject.send(null)}if(requestObject.status==200){var evalFunct=
successFunction+"(requestObject.responseXML);";if(successFunction.indexOf("(")>-1)evalFunct=successFunction.substring(0,successFunction.length-1)+",requestObject.responseXML);";eval(evalFunct)}else eval(failureFunction)}}
function makeTabsClickable(){$.each($("a.navTab"),function(i,e){try{$(e).parent().prev().addBack().next().addBack().makeLink($(e).attr("href"))}catch(err){}});$.each($("a.verticalTabText"),function(i,e){try{$(e).parent().parent().prev().addBack().next().addBack().makeLink($(e).attr("href"))}catch(err){}});if(!isFirefox()||typeof moving=="undefined")$.each($("a.templateTabText"),function(i,e){if(!$(e).attr("href").startsWith("#"))$(e).parent().makeLink($(e).attr("href"));else $(e).parent().hover(function(){$(this).css({"cursor":"pointer"})}).click($(e).attr("onclick"))})}
function matchWidth(objectToMatchId,objectToSetId,offset){var sourceWidth=$(objectToMatchId).width();if(offset)sourceWidth+=offset;$(objectToSetId).width(sourceWidth)}function parseBrowserUrlPath(){var url=window.location.href;var queryArgs="";if(url.lastIndexOf("?")>0)queryArgs=url.substring(url.lastIndexOf("?"),url.length);var pathname=window.location.pathname;var referrer=pathname+queryArgs;return referrer}
function parseUri(uri){var o=parseUri.options,m=o.parser[o.strictMode?"strict":"loose"].exec(uri),uri={},i=14;while(i--)uri[o.key[i]]=m[i]||"";uri[o.q.name]={};uri[o.key[12]].replace(o.q.parser,function($0,$1,$2){if($1)uri[o.q.name][$1]=$2});uri["action"]=uri.file.substr(0,uri.file.indexOf(".do")+3);return uri}
function parseUrlParams(url){var urlParamsString=url.substring(url.search("\\?")+1);return urlParamsString.split("&").reduce(function(result,value){var tmp=value.split("=");result[tmp[0]]=tmp[1];return result},{})}function pollResults(details){schedulingProcessRefreshEvent=false;disableForm(document.forms[0]);startProgressMeter(details);setTimeout("doSubmitRefreshEvent(2210, document.forms[0])",5E3)}
function popupClose(){if(popup!=null&&!popup.closed&&!popupBlocked&&typeof popup.popupClose=="function")popup.popupClose();if(popupSaved!=null){popupSaved.x2opener=x2opener;popupSaved=null}if(this!=getParentX2Window()&&!popupBlocked)this.close()}
function removeFromDelimitedList(list,value,delimiter){var newList="";var separation=",";if(delimiter!=null)separation=delimiter;var existingValues=list.split(separation);for(var i=0;i<existingValues.length;i++)if(value!=existingValues[i])newList=addToDelimitedList(newList,existingValues[i]);return newList}
function removeHTML(html){html=html.replace(/<\/?[^>]+(>|$)/g,"");html=html.replace(/&nbsp;*/g," ");html=html.replace(/&quot;*/g,'"');html=html.replace(/&amp;*/g,"&");html=html.replace(/&lt;/g,"<");html=html.replace(/&gt;/g,">");return html}
function replaceSelection(input,replaceString){if(input.setSelectionRange){var selectionStart=input.selectionStart;var selectionEnd=input.selectionEnd;input.value=input.value.substring(0,selectionStart)+replaceString+input.value.substring(selectionEnd);if(selectionStart!=selectionEnd)setSelectionRange(input,selectionStart,selectionStart+replaceString.length);else setSelectionRange(input,selectionStart+replaceString.length,selectionStart+replaceString.length)}else if(document.selection){var range=
document.selection.createRange();if(range.parentElement()==input){var isCollapsed=range.text=="";range.text=replaceString;if(!isCollapsed){range.moveStart("character",-replaceString.length);range.select()}}}}
function resetSessionTimeout(params){var parentWin=getParentX2Window();if(parentWin!=null&&typeof parentWin!="undefined"&&this!=parentWin&&typeof parentWin.resetSessionTimeout=="function")parentWin.resetSessionTimeout(params);else{var timeoutAsString=null;var nextSessionTimeout=null;if(params!=null&&params.substring){var paramArray=params.split(",");timeoutAsString=paramArray[0];nextSessionTimeout=parseInt(paramArray[1])}else timeoutAsString=params;if(timeoutDuration>0||timeoutAsString!=null){if(timeoutAsString!=
null)timeoutDuration=parseInt(timeoutAsString)*1E3;if(nextSessionTimeout!=null)parentWin.sessionTimeout=nextSessionTimeout;else parentWin.sessionTimeout=timeoutDuration+(new Date).getTime();updateSessionTimeout()}}}
function resizeBlobTextArea(extraHeight,elementId){var documentWidth=document.body.clientWidth;var documentHeight=document.body.clientHeight;if(elementId==null)elementId="blobTextArea";var blobTextArea=document.getElementById(elementId);if(blobTextArea!=null){var extraWindowHeight=125;if(extraHeight!=null)extraWindowHeight+=extraHeight;blobTextArea.style.width=documentWidth-35;blobTextArea.style.height=documentHeight-extraWindowHeight}}
function resizePopupWindowToFitContent(theWindow){var theDocument=theWindow.document;var contentWidth=$(theDocument).width();var contentHeight=$(theDocument).height();var windowInnerWidth=theWindow.innerWidth;var windowInnerHeight=theWindow.innerHeight;var windowOuterWidth=theWindow.outerWidth;var windowOuterHeight=theWindow.outerHeight;var windowChromeWidth=windowOuterWidth-windowInnerWidth;var windowChromeHeight=windowOuterHeight-windowInnerHeight;if(contentWidth>windowInnerWidth)windowOuterWidth=
Math.min(contentWidth+windowChromeWidth,window.screen.availWidth);if(contentHeight>windowInnerHeight)windowOuterHeight=Math.min(contentHeight+windowChromeHeight,window.screen.availHeight);if(windowOuterHeight!=theWindow.outerHeight||windowOuterWidth!=theWindow.outerWidth)theWindow.resizeTo(windowOuterWidth,windowOuterHeight);var clippedWidth=Math.min(window.screen.availWidth-(windowOuterWidth+theWindow.screenX-window.screen.availLeft),0);var clippedHeight=Math.min(window.screen.availHeight-(windowOuterHeight+
theWindow.screenY-window.screen.availTop),0);theWindow.moveBy(clippedWidth,clippedHeight)}function rewriteUrl(url){url=url.replaceAll("\\","%5C");url=url.replaceAll("^","%5E");url=url.replaceAll("`","%60");url=url.replaceAll("{","%7B");url=url.replaceAll("|","%7C");url=url.replaceAll("}","%7D");var paramsExist=url.lastIndexOf("?");if(paramsExist>0){var parts=url.split("?");if(parts.length==2)url=parts[0]+"?"+parts[1].replaceAll(":","%3A").replaceAll("[","%5B").replaceAll("]","%5D")}return url}
function saveFormFocus(focusId){$("#formFocusField").val(focusId)}function saveFormFocusFromUrl(url){var uri=parseUri(url);if(uri&&uri.queryKey&&uri.queryKey.property)saveFormFocus("#"+uri.queryKey.property)}function saveScrollCoordinates(){var form=document.forms[0];var xy=getScrollCoordinates();form.scrollX.value=xy[0];form.scrollY.value=xy[1]}
function scrollToCoordinates(){var form=document.forms[0];if(form==null)form=this;window.scrollTo(form.scrollX?form.scrollX.value:0,form.scrollY?form.scrollY.value:0)}
function sessionTimedOut(){popupClose();EmbeddedPopup.popupManager.setBackgroundOpacity(90);setThisContentArea("");closeMessageWindow();EmbeddedPopup.popupManager.closeCover();window.onbeforeunload="";document.onclick="";var timedMessage=sessionExpiredMessage+" "+getCurrentTime();makeAsynchronousTextRequest("logoutSession.do","doNothing","doNothing");showAlertWindow(timedMessage,false,null,"button.continue","window.open('logon.do', '_top');")}
function sessionTimedOut(){popupClose();EmbeddedPopup.popupManager.setBackgroundOpacity(90);setThisContentArea("");closeMessageWindow();EmbeddedPopup.popupManager.closeCover();window.onbeforeunload="";document.onclick="";var timedMessage=sessionExpiredMessage+" "+getCurrentTime();makeAsynchronousTextRequest("logoutSession.do","doNothing","doNothing");showAlertWindow(timedMessage,false,null,"button.continue","window.open('logon.do', '_top');")}
function setBit(form,property,indexAsString,value,forcedLengthAsString){var index=parseInt(indexAsString);var bitString=form.elements[property].value;if(forcedLengthAsString!=null){var forcedLength=parseInt(forcedLengthAsString);var padAmount=forcedLength-bitString.length;for(var i=0;i<padAmount;i++)bitString+="0"}if(index>=0&&index<=bitString.length){var prefix=bitString.substring(0,index);var newValue=value?"1":"0";var suffix=bitString.substring(1+index,bitString.length);form.elements[property].value=
prefix+newValue+suffix}}function setBooleanAsStringValue(hiddenProperty,checkbox){checkbox.form.elements[hiddenProperty].value=checkbox.checked?"1":"0"}function setBooleanValue(hiddenProperty,checkbox){checkbox.form.elements[hiddenProperty].value=checkbox.checked.toString()}function setBooleanValueFromList(hiddenProperty,selectElement){var selectedValue=selectElement.options[selectElement.selectedIndex].value;selectElement.form.elements[hiddenProperty].value=selectedValue}
function setCSRFProtection(url){var token=$('input[name^="org\\.apache\\.struts\\.taglib\\.html\\.TOKEN"]').val();var separator=url.indexOf("?")>-1?"&":"?";url+=separator+encodeURIComponent("org.apache.struts.taglib.html.TOKEN")+"="+encodeURIComponent(token);return url}function setThisContentArea(htmlData){var textArea=document.getElementById("contentArea");if(textArea!=null)textArea.innerHTML=htmlData}
function setDefaultFocus(form){var hasFocus=$('input:visible:enabled[type="text"], select:visible:enabled').is(":focus");if(!hasFocus){var element=null;var fieldId=$("#formFocusField").val();if(fieldId.length>0){var dom=document.getElementById(fieldId);if(dom==null){var byName=document.getElementsByName(fieldId);if(byName.length>0)dom=byName[0]}if(dom!=null)element=$(dom)}if(element==null||element.length==0)element=$(':input:visible:enabled[type="text"]:first');if(element.length>0)setTimeout(function(){element.focus()},
0)}if(isInternetExplorer())if(popup!=null)try{popup.focus()}catch(e){}}function setHomeroomTeacherView(text){var parameters=text.split(":",3);var teacherViewElement=document.getElementById("homeroomTeacherView"+parameters[0]+parameters[1]);teacherViewElement.innerHTML=parameters[2];teacherViewElement=document.getElementById(parameters[0]+"-span");if(teacherViewElement!=null)teacherViewElement.innerHTML=parameters[2]}
function setInitialMaximizedState(maximizeTitle,minimizeTitle){var form=getPrimaryForm();if(typeof $("input[name=maximized]")!=="undefined"){var maximized="true"===$("input[name=maximized]").val();setupMaximizeMode(maximized,maximizeTitle,minimizeTitle,form)}}function setOpacity(opacity,id){var object=document.getElementById(id).style;object.opacity=opacity/100;object.MozOpacity=opacity/100;object.KhtmlOpacity=opacity/100;object.filter="alpha(opacity="+opacity+")"}
function setSelectionRange(input,selectionStart,selectionEnd){if(input.setSelectionRange){input.focus();input.setSelectionRange(selectionStart,selectionEnd)}else if(input.createTextRange){var range=input.createTextRange();range.collapse(true);range.moveEnd("character",selectionEnd);range.moveStart("character",selectionStart);range.select()}}
function shim(divId){var divElement=getElementByIdSafe(divId);var iframeElement=getElementByIdSafe(divId+"Shim");if(isInternetExplorer()&&iframeElement!=null){iframeElement.style.width=divElement.offsetWidth;iframeElement.style.height=divElement.offsetHeight;iframeElement.style.top=divElement.currentStyle.top;iframeElement.style.left=divElement.currentStyle.left;iframeElement.style.zIndex=divElement.currentStyle.zIndex-1;iframeElement.style.display="block"}}
function showContentItem(contentItemOid,ariOid,args,callback){var url="contentDce.do?userEvent=2450&contentItemOid="+contentItemOid;if(ariOid)url+="&ariOid="+ariOid;if(args)url+=args;var win=window.open(rewriteUrl(url),"mywindow","width=800,height=700,toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,copyhistory=yes,resizable=yes");if(callback)callback()}
function assignmentShowContentItem(contentItemOid,ariOid,i,contextPath,docPrefix){if(reqInProgress)return;var documentPrefixPlaceHolder=document.getElementById(docPrefix+contentItemOid);if(documentPrefixPlaceHolder!=null){var openingText=grabResource("label.classes.opening");documentPrefixPlaceHolder.innerHTML="<img src='images/loading.gif'/> "+openingText+"&nbsp;"}getContentUrl(contentItemOid,ariOid,false,contextPath,docPrefix);if(canPost)canPost[i]=true}
function getContentUrl(contentItemOid,ariOid,args,contextPath,docPrefix){var url="contentDce.do?userEvent=2570&contentItemOid="+contentItemOid;if(ariOid)url+="&ariOid="+ariOid;if(args)url+=args;reqInProgress=true;$.ajax({type:"POST",url:rewriteUrl(url),success:function(jsonResponseTxt){var ignoreThisResponse=false;if(jsonResponseTxt!=null&&jsonResponseTxt.trim().length===0)return;var jsonResponse=jQuery.parseJSON(jsonResponseTxt);if(jsonResponse.success==true){var contentUrl=jsonResponse.message.trim();
if(contentUrl.length===0)ignoreThisResponse=true;else{if(contentUrl.indexOf("http")!=0&&contextPath!==undefined)contentUrl=contextPath+contentUrl;var win=window.open(rewriteUrl(contentUrl),"mywindow","width=800,height=700,toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,copyhistory=yes,resizable=yes");if(contentUrl.indexOf(".google.")!=-1)sendEvent(getGDAAction().EVENT_GOOGLE_DRIVE_USE_DOC_OPEN_REQUEST,getGDALabel().LABEL_GOOGLE_DRIVE_ACCESS_FROM_ASSIGNMENT_ATTACHMENT)}}else{showMessageWindow(jsonResponse.message,
true,false,275);sendEvent(getGDAAction().EVENT_GOOGLE_DRIVE_USE_DOC_OPEN_REQUEST_FAILED,appendMessageToLabel(getGDALabel().LABEL_GOOGLE_DRIVE_ACCESS_FROM_ASSIGNMENT_ATTACHMENT,jsonResponse.message))}if(!ignoreThisResponse){reqInProgress=false;var documentPrefixPlaceHolder=document.getElementById(docPrefix+contentItemOid);if(documentPrefixPlaceHolder!=null)documentPrefixPlaceHolder.innerHTML=""}},error:function(jsonResponseTxt){reqInProgress=false;var documentPrefixPlaceHolder=document.getElementById(docPrefix+
contentItemOid);if(documentPrefixPlaceHolder!=null)documentPrefixPlaceHolder.innerHTML=""}})}function showLoadingCover(container){var loadingCover=document.getElementById("loadingCover");loadingCover.style.left=findPositionX(container);loadingCover.style.top=findPositionY(container);loadingCover.style.width=container.offsetWidth;loadingCover.style.height=getWindowHeight()-115;$("#loadingCover").show()}
function showAjaxErrorMessage(data){var errorMessage="";var stackTrace=data.stackTrace;errorMessage+="<strong>";if(stackTrace)errorMessage=grabResource("error.system.error");else errorMessage=grabResource("message.request.error");errorMessage+="</strong><br/><br/>";if(data.reason){errorMessage+=data.reason;errorMessage+="<br/>"}if(stackTrace)for(var i=0;i<stackTrace.length;i++){var stackTraceObj=stackTrace[i];for(var p in stackTraceObj)errorMessage+=p+": "+stackTraceObj[p]+" ";errorMessage+="<br/>"}showMessageWindow(errorMessage,
true,false,600,null,600)}function smellCookie(cookieName){var value=null;var cookies=document.cookie.split(";");for(var i=0;i<cookies.length;i++){var cookie=cookies[i];var index=cookie.indexOf(cookieName+"=");if(index>-1){value=cookie.substring(index+cookieName.length+1,cookie.length);break}}return value}
function stopBrowserEvent(theEvent){if(!theEvent.ctrlKey&&!theEvent.shiftKey&&theEvent.type=="keyup"&&theEvent.keyCode!=13)alert(grabResource("message.truncate.limit"));if(theEvent.preventDefault)theEvent.preventDefault();else theEvent.returnValue=false;return false}
function textDivShow(bodyText,headerText){textDivHide();var windowHeight=getWindowHeight();var windowWidth=getWindowWidth();var divHeight=300;var divWidth=500;var textDiv=document.createElement("div");textDiv.style.position="absolute";textDiv.style.top=windowHeight/2-divHeight/2;textDiv.style.left=windowWidth/2-divWidth/2;textDiv.style.width=divWidth+"px";textDiv.style.height=divHeight+"px";textDiv.id="textDisplay";textDiv.className="textDisplayBox blobTextReadOnly";if(headerText==null)headerText=
"";textDiv.innerHTML='<table border="0" class="textDisplayBoxHeaderTable"><tr><td class="textDisplayBoxHeaderCell">'+headerText+' </td><td class="textDisplayBoxHeaderCell"><button type="button" onclick="javascript:textDivHide();" class="textDisplayBoxCloseButton">Close</button></td>'+"</tr></table>"+'<div class="textDisplayInnerBody">'+bodyText+"</div>";$(textDiv).hide().appendTo(document.body);$(textDiv).stop().fadeIn(200)}
function textDivHide(){$("#textDisplay").stop().fadeOut(200,function(){$("#textDisplay").remove()})}
function tickleServer(){if(getParentX2Window().popup==self)getParentX2Window().tickleServer();else{var lastTickle=sessionTimeout-timeoutDuration;var nowTickle=(new Date).getTime();var nextSessionTimeout;var lastAccessTimeOffset=parseInt((nowTickle-lastUserEvent)/1E3,10);if(lastUserEvent==0)nextSessionTimeout=nowTickle+timeoutDuration;else{var lastAccessDiff=lastUserEvent-lastTickle;nextSessionTimeout=sessionTimeout+lastAccessDiff}for(var i=0;i<3;i++)makeAsynchronousTextRequest("tickle.do?lastAccessTimeOffset="+
lastAccessTimeOffset+"&nextSessionTimeout="+nextSessionTimeout,"resetSessionTimeout",'doSelfRedirect("'+document.location+'")')}}
function setupMaximizeMode(maximized,maximizeTitle,minimizeTitle,form){if(maximized)$("#maximizeMenuButton").hover(function(){$(this).addClass("c2background")},function(){$(this).removeClass("c2background")}).parent().show();else $("#maximizeMenuButton").parent().hide();$("#topTitleBar").css("display",maximized?"none":"");$("#actualTopMenuBar").css("position",maximized?"absolute":"");var topMenuBar=$("#topMenuBar");setupMaximizedMenus(maximized,topMenuBar);topMenuBar.css("width",maximized?"100%":
"");var layoutVerticalTabs=$("#layoutVerticalTabs");setupMaximizedMenus(maximized,layoutVerticalTabs);$("#layoutVerticalTabsContainer").css({"width":maximized?"3px":"100px","minWidth":maximized?"3px":"100px"});if(document.getElementById("dataGrid")!=null){UNAVAILABLE_WIDTH=maximized?30:125;resizeGrid("dataGrid")}else if(window.scrollTable){UNAVAILABLE_WIDTH=maximized?10:125;UNAVAILABLE_HEIGHT=maximized?130:217;scrollTable()}var aElements=document.getElementsByTagName("a");for(var i=0;i<aElements.length;i++){var aElement=
aElements[i];if(aElement.id.startsWith("link_"))aElement.href=updateMaximizedParam(aElement.href,maximized)}for(var optionId in optionsById){var option=optionsById[optionId];option.action=updateMaximizedParam(option.action,maximized)}updateMaximizedImage(maximized,maximizeTitle,minimizeTitle);form.elements["maximized"].value=maximized}
function getPrimaryForm(){var form=document.forms[0];if(form.primaryForm&&form.primaryForm.value=="false")for(var i=0;i<document.forms.length;i++){form=document.forms[i];if(form.primaryForm&&form.primaryForm.value=="true")break}return form}
function toggleMaximize(maximizeTitle,minimizeTitle){var form=getPrimaryForm();if(form.elements["maximized"]!=null){var wasMaximized="true"===form.elements["maximized"].value;var maximized=!wasMaximized;setupMaximizeMode(maximized,maximizeTitle,minimizeTitle,form);var url="maximizeDisplay.do?newMaximizeState="+(maximized?"maximize":"minimize");$.ajax({type:"POST",url:rewriteUrl(url),success:function(){}})}}
function setupMaximizedMenus(maximized,menu){if(!maximized)menu.css({"position":"","zIndex":"","width":""}).show();else menu.css({"display":"none","position":"fixed","zIndex":"1000"}).hide()}
function showMaximizeMenus(event){var SLIDE_SPEED=300;var TOP_BAR_HEIGHT=30;event.stopPropagation();var topMenuBar=$("#topMenuBar");topMenuBar.css("height",TOP_BAR_HEIGHT).show("slide",{direction:"up",queue:false},SLIDE_SPEED);var actualTopMenuBar=$("#actualTopMenuBar");if(actualTopMenuBar.width()<actualTopMenuBar[0].scrollWidth){$("#topMenuBarLeft").show();$("#topMenuBarRight").show()}var setCss=function(){if($("#layoutVerticalTabs").length>0){var windowHeight=window.innerHeight-TOP_BAR_HEIGHT;var tabsHeight=
$("#layoutVerticalTabs").height();$("#layoutVerticalTabs").css({"top":TOP_BAR_HEIGHT,"overflowY":windowHeight>tabsHeight?"":"auto","height":windowHeight>tabsHeight?"":Math.min(windowHeight,tabsHeight).toString(),"width":135,"overflowX":"hidden"});$("#fillerRow").removeClass("borderRight")}};$("#layoutVerticalTabs").show("slide",{direction:"left",queue:false},SLIDE_SPEED,setCss);setCss();var overlay=document.getElementById("overlay");if(overlay!=null)$("#overlay").show();var resizeEventHandler=function(event){var layoutVerticalTabs=
document.getElementById("layoutVerticalTabs");if(layoutVerticalTabs!==null)$("#layoutVerticalTabs").css("height",Math.min(window.innerHeight-TOP_BAR_HEIGHT,layoutVerticalTabs.scrollHeight).toString());var actualTopMenuBar=$("#actualTopMenuBar");if(actualTopMenuBar.width()<actualTopMenuBar[0].scrollWidth){$("#topMenuBarLeft").show();$("#topMenuBarRight").show()}else{$("#topMenuBarLeft").hide();$("#topMenuBarRight").hide()}};var outsideMenuHandler=function(event){var $target=$(event.target);if(!$target.closest("#layoutVerticalTabs").length&&
!$target.closest("#topMenuBar").length)closeMaximizeMenus()};var escapeKeyHandler=function(event){if(event.key==="Escape"||event.key==="Esc"||event.keyCode===27){closeMaximizeMenus();event.preventDefault();return false}};var rightMenuClickHandler=function(event){var bar=$("#actualTopMenuBar");bar.scrollLeft(bar.scrollLeft()+bar.width());event.stopPropagation()};var leftMenuClickHandler=function(event){var bar=$("#actualTopMenuBar");bar.scrollLeft(Math.max(0,bar.scrollLeft()-bar.width()));event.stopPropagation()};
function closeMaximizeMenus(){$("#layoutVerticalTabs").hide("slide",{direction:"left"},SLIDE_SPEED,function(){$("#layoutVerticalTabs").css({"overflowY":"","height":""})});$("#fillerRow").addClass("borderRight");$("#topMenuBar").hide("slide",{direction:"up"},SLIDE_SPEED);setTimeout(function(){topMenuBar.css("height","");$("#topMenuBarLeft").hide();$("#topMenuBarRight").hide()},1E3);$("#overlay").hide();$(document).off("click",outsideMenuHandler).off("keydown",escapeKeyHandler);$(window).off("resize",
resizeEventHandler);$("#topMenuBarRight").off("click",rightMenuClickHandler);$("#topMenuBarLeft").off("click",leftMenuClickHandler)}$(document).on("click",outsideMenuHandler).on("keydown",escapeKeyHandler);$(window).on("resize",resizeEventHandler);$("#topMenuBarRight").on("click",rightMenuClickHandler);$("#topMenuBarLeft").on("click",leftMenuClickHandler)}
function trackFormFocus(){$("form").each(function(index,form){$(form).find("input[type=text], textarea, select").on("focus",function(){var focusId=$(this).attr("id");if(!focusId||focusId.length==0||focusId.indexOf("&")>0)focusId=$(this).attr("name");if(focusId)saveFormFocus(focusId)})})}
function trimField(field,maxLength,showConfirm){if(field.truncate){var callTruncate=function(){field.truncate(showConfirm)};setTimeout(callTruncate,100)}else if(field.value.length>maxLength){var truncateText=true;if(showConfirm&&!confirm(grabResource("message.truncate.warning")))truncateText=false;if(truncateText){alert(grabResource("message.truncate.error"));field.value=field.value.substring(0,maxLength)}}}
function truncateText(theEvent,field,maxLength){theEvent=theEvent||window.event;var showConfirm=true;if(theEvent)if(theEvent.type=="paste"||theEvent.type=="input"){showConfirm=false;var pasteContent=theEvent.clipboardData&&theEvent.clipboardData.getData?theEvent.clipboardData.getData("text/plain"):window.clipboardData&&window.clipboardData.getData("Text")?window.clipboardData.getData("Text"):false;if(pasteContent){field.value+=pasteContent;trimField(field,maxLength,showConfirm);return stopBrowserEvent(theEvent)}}trimField(field,
maxLength,showConfirm)}function unShim(divId){var iframeElement=getElementByIdSafe(divId+"Shim");if(isInternetExplorer()&&iframeElement!=null)iframeElement.style.display="none"}function updateHomeroomTeacherView(fieldID,schoolId,studentOid){var homeroom=document.getElementById(fieldID).value;makeAsynchronousTextRequest("homeroomTeacherView.do?fieldId="+fieldID+"&schoolOid="+schoolId+"&homeroom="+homeroom+"&studentOid="+studentOid,setHomeroomTeacherView)}
function updateInputControl(formName,elementName,enable){var control=document.forms[formName].elements[elementName];control.disabled=!enable;var sibling=control.parentNode.parentNode.lastChild.firstChild;if(sibling!=null&&sibling.tagName=="A")sibling.style.display=enable?"block":"none"}
function updateMaximizedParam(url,maximized){var maximizedParam="maximized="+maximized;if(url!=null)if(url.indexOf("maximized")!=-1)url=url.replace("maximized="+maximized,maximizedParam);else if(url.indexOf("?")!=-1)url=url.replace("?","?"+maximizedParam+"&");else if(url.indexOf(".do")!=-1)url=url.replace(".do",".do?"+maximizedParam);return url}
function updateMaximizedImage(maximized,maximizeTitle,minimizeTitle){var image=document.getElementById("maximizeImg");if(maximized){image.src="images/restore-window.gif";image.title=minimizeTitle}else{image.src="images/max-window.gif";image.title=maximizeTitle}}
function updateSessionTimeout(){var nowUpdate=(new Date).getTime();var nextUpdate=6E4;if(nowUpdate>sessionTimeout-75E3){var hWin=getTopWindowHandle();if(hWin.lastUserEvent>0&&nowUpdate-hWin.lastUserEvent<nextUpdate){tickleServer();nextUpdate=nextUpdate-(nowUpdate-hWin.lastUserEvent);hWin.lastUserEvent=0;nowUpdate=0}else{var timeoutMessage=getTimeoutMessage();hWin.showAlertWindow(timeoutMessage,false,null,"button.continue","getRootX2Window().lastUserEvent = new Date().getTime(); tickleServer();");
setTimeout("updateTimeoutClock()",1E3)}}if(sessionTimeout>nowUpdate){if(idSessionTimeout!=0)clearTimeout(idSessionTimeout);idSessionTimeout=setTimeout("updateSessionTimeout()",nextUpdate)}}
function updateTimeDuration(elementName){var days="0"+document.getElementById(elementName+"_days").value;var hours="0"+document.getElementById(elementName+"_hours").value;var minutes="0"+document.getElementById(elementName+"_minutes").value;var duration=days+":"+hours+":"+minutes;document.forms[0].elements[elementName].value=duration}
function updateTimeoutClock(){var hWin=getTopWindowHandle();var clockArea=hWin.document.getElementById("timeoutClock");if(clockArea){var parentWin=getParentX2Window();var seconds=Math.round((sessionTimeout-(new Date).getTime())/1E3);var html=seconds+getTimerAnimation(seconds,5);clockArea.innerHTML=html;if((sessionTimeout-(new Date).getTime())/1E3<1)parentWin.setTimeout("sessionTimedOut()",1E3);else parentWin.setTimeout("updateTimeoutClock()",1E3)}}
function updateTableLockTimeoutClock(){var hWin=getTopWindowHandle();var clockArea=hWin.document.getElementById("tableLockTimeoutClock");if(clockArea){var parentWin=getParentX2Window();clearTimeout(parentWin.tableLockTimeoutHandle);parentWin.tableLockTimeoutHandle=null;var seconds=Math.round((tableLockTimeout-(new Date).getTime())/1E3);var html=seconds+getTimerAnimation(seconds,5);clockArea.innerHTML=html;if((tableLockTimeout-(new Date).getTime())/1E3>=1)if(parentWin.tableLockTimeoutHandle==null)parentWin.tableLockTimeoutHandle=
setTimeout("updateTableLockTimeoutClock()",1E3)}}function validateEmail(email){var regEx=/.+\@.+\..+/;var validated=false;if(email!=null)if(regEx.exec(email)!=null)validated=true;return validated}function validateNumeric(val){return!isNaN(parseFloat(val))&&isFinite(val)}
function validateInteger(evt){var theEvent=evt||window.event;var key=theEvent.keyCode||theEvent.which;key=String.fromCharCode(key);var regex=/[0-9]|[\x08\x09\x0D\x10\x25\x27\x23\x24]/;if(!regex.test(key)){theEvent.returnValue=false;theEvent.preventDefault()}}function verifySelection(control){var selected=false;if(control!=null){var controls=forceElementToArray(control);for(var i=0;i<controls.length;i++)if(controls[i].checked){selected=true;break}}return selected}
function EmbeddedPopup(){this.showingFrame=false;this.documentNode=null;this.bodyNode=null;this.divNode=null;this.iframeNode=null}
EmbeddedPopup.prototype.open=function(pUrl,pWidth,pHeight,pTop,pForceHeight,pZ_Position){this.initialize();if(!this.showingFrame&&this.iframeNode!=null&&this.divNode!=null){this.url=rewriteUrl(pUrl);this.width=pWidth;this.height=pHeight;this.top=pTop;var windowWidth=document.body.clientWidth;if(this.width>windowWidth-50)this.width=windowWidth-50;var left=(windowWidth-this.width)/2;var windowHeight=getWindowHeight();if(!pForceHeight&&this.height>windowHeight-50)this.height=windowHeight-50;if(pTop==
-1){var top=(windowHeight-this.height)/2;this.top=top}if(pZ_Position!=null)this.iframeNode.style.zIndex=pZ_Position;this.divNode.style.display="block";this.iframeNode.style.left=left+"px";this.iframeNode.style.top=parseInt(this.top)+getScrollCoordinates()[1]+"px";this.iframeNode.style.width=this.width+"px";this.iframeNode.style.height=this.height+"px";this.iframeNode.style.display="block";this.iframeNode.src=this.url;if(isMozilla())elementAddListener(this.documentNode,"focus",this.onfocus);else{var elms=
[];if(this.documentNode.forms[0]!==undefined)elms=this.documentNode.forms[0].elements;for(var idx=0;idx<elms.length;idx++){var elm=elms[idx];if(elm.getAttribute("type")!="hidden")elementAddListener(elm,"focus",this.onfocus)}}this.showingFrame=true;this.iframeNode.focus()}};EmbeddedPopup.prototype.openCover=function(){this.initialize();if(!this.showingFrame&&this.divNode!=null){this.divNode.style.display="block";this.showingFrame=true}};
EmbeddedPopup.prototype.setBackgroundOpacity=function(percentage){if(this.divNode!=null)fadeOpacity(this.divNode.id,60,percentage,1E3)};
EmbeddedPopup.prototype.initialize=function(){if(!this.showingFrame&&(this.bodyNode==null||this.iframeNode==null||this.divNode==null)){this.documentNode=document;this.bodyNode=document.body;this.divNode=document.createElement("div");this.divNode.id="embeddedCover";this.divNode.className="embeddedCoverClass";this.divNode.style.display="none";this.bodyNode.appendChild(this.divNode);this.iframeNode=document.createElement("iframe");this.iframeNode.id="embeddedFrame";this.iframeNode.className="embeddedFrameClass";
this.iframeNode.style.display="none";this.bodyNode.appendChild(this.iframeNode)}};
EmbeddedPopup.prototype.close=function(){if(this.showingFrame&&this.iframeNode!=null&&this.divNode!=null){this.iframeNode.style.display="none";this.iframeNode.src="about:blank";this.divNode.style.display="none";if(isMozilla())elementRemoveListener(this.documentNode,"focus",this.onfocus);else{var elms=[];if(this.documentNode.forms[0]!==undefined)elms=this.documentNode.forms[0].elements;for(var idx=0;idx<elms.length;idx++){var elm=elms[idx];if(elm.getAttribute("type")!="hidden")elementRemoveListener(elm,
"focus",this.onfocus)}}this.showingFrame=false}else if(window.parent!=window)window.parent.EmbeddedPopup.popupManager.close()};EmbeddedPopup.prototype.closeCover=function(){if(this.showingFrame&&this.divNode!=null){this.divNode.style.display="none";this.showingFrame=false}};
EmbeddedPopup.prototype.onfocus=function(e){if(EmbeddedPopup.popupManager.showingFrame&&EmbeddedPopup.popupManager.iframeNode!=null&&EmbeddedPopup.popupManager.bodyNode!=null){var elements;if(EmbeddedPopup.popupManager.iframeNode.contentDocument!=null&&EmbeddedPopup.popupManager.iframeNode.contentDocument.forms.length>0)elements=EmbeddedPopup.popupManager.iframeNode.contentDocument.forms[0].elements;else if(EmbeddedPopup.popupManager.iframeNode.contentWindow!=null)if(EmbeddedPopup.popupManager.iframeNode.contentWindow.document.forms.length>
0)elements=EmbeddedPopup.popupManager.iframeNode.contentWindow.document.forms[0].elements;if(elements!=null)for(var idx=0;idx<elements.length;idx++){var elm=elements[idx];if(elm.getAttribute("type")!="hidden"){elm.focus();return}}}};String.prototype.endsWith=function(suffix){return this.indexOf(suffix,this.length-suffix.length)!==-1};String.prototype.escapeRegExp=function(){return this.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&")};
String.prototype.fillDelimited=function(){var filledResource=this;for(var i=0;i<arguments.length;i++){var regexString="\\{"+i+"\\}";var regex=new RegExp(regexString,"g");var replace=arguments[i]==null?"":arguments[i];replace=replace.replace(/\$/g,"$$$$");filledResource=filledResource.replace(regex,replace)}return filledResource};String.prototype.isNumeric=function(){return!isNaN(parseFloat(this))&&isFinite(this)};
String.prototype.pad=function(padChar,width,isLeft){width-=this.length;if(width>0)if(isLeft)return(new Array(width+(/\./.test(this)?2:1))).join(padChar)+this;else return this+(new Array(width+(/\./.test(this)?2:1))).join(padChar);return this+""};String.prototype.replaceAll=function(target,replacement){return this.split(target).join(replacement)};String.prototype.startsWith=function(str){return this.substr(0,str.length)===str};
String.prototype.trim=function(){return this.replace(/^\s*/,"").replace(/\s*$/,"")};String.prototype.truncate=function(length){if(this&&this.length>length&&length>0)return this.substring(0,length-3)+"...";return this+""};
function launchToVendor(widgetOid){var params={widgetOid:widgetOid};$.ajax({url:"launchToVendor.do",type:"post",useDefaultXhrHeader:false,data:params,dataType:"json"}).done(function(data){if(data.success===false)alert('<bean:message key="message.launchToVendorWidget.ajax.error" />');else window.open(data.url)})}
function resizeTopTabsScrolling(){if(isCurrentNavTabPage()){var div=$("#topTabs");if(div.length>0){var verticalScrollWidth=window.innerWidth-document.documentElement.clientWidth;var availableWidth=getWindowWidth()-verticalScrollWidth;div.width(availableWidth);var leftScrollButton=$("#left-arrow-container");var rightScrollButton=$("#right-arrow-container");if(div.find("tr")[0].scrollWidth>availableWidth){leftScrollButton.css("display","inline-block");rightScrollButton.css("display","inline-block");
leftScrollButton.css("border-right","1px solid black");rightScrollButton.css("border-left","1px solid black");leftScrollButton.css("height",div.height());rightScrollButton.css("height",div.height());div.width(availableWidth-leftScrollButton.outerWidth(true)-rightScrollButton.outerWidth(true));var selectedTab=$(".navTabBackgroundSelected:first");if(selectedTab.length>0)div.scrollLeft(div.scrollLeft()+selectedTab.position().left-leftScrollButton.outerWidth(true))}else{leftScrollButton.hide();rightScrollButton.hide()}}}}
function resizeTopTabsScrollingAfterWindowResized(){if(isCurrentNavTabPage()){var div=$("#topTabs");var verticalScrollWidth=window.innerWidth-document.documentElement.clientWidth;var availableWidth=getWindowWidth()-verticalScrollWidth;var leftScrollButton=$("#left-arrow-container");var rightScrollButton=$("#right-arrow-container");if(div.find("tr")[0].scrollWidth>availableWidth)if(document.documentElement.clientWidth-leftScrollButton.outerWidth(true)-rightScrollButton.outerWidth(true)>div.width())div.width(document.documentElement.clientWidth-
leftScrollButton.outerWidth(true)-rightScrollButton.outerWidth(true))}}function startScrollingTopTabs(type,event){preventBordersCollision();$("#topTabs").animate({scrollLeft:type+"="+10},1,"linear",function(){startScrollingTopTabs(type,event)});event.preventDefault()}function stopScrollingTopTabs(){$("#topTabs").stop()}
function isCurrentNavTabPage(){var selectedNav=document.getElementsByClassName("navTabBackgroundSelected")[0];var div=$("#topTabs");if(selectedNav===undefined)return false;if(selectedNav.isEqualNode(div.find("td")[0]))return true;return false}
function preventBordersCollision(){var rightScrollButton=$("#right-arrow-container");var lastNavTabRight=$(".navTab:last").offset().left+$("navTab:last").width();if(rightScrollButton.position().left>lastNavTabRight)rightScrollButton.css("border","none");else rightScrollButton.css("border-left","1px solid black")}
function resizeSideScrolling(){var div=$("#pageMenuContainer");if(div.length>0){var topNav=$("#topNav");var header=$("#header");var availableHeight=getWindowHeight()-topNav.outerHeight(true)-header.outerHeight(true)-8;div.height(availableHeight);var upScrollButton=$("#sideMenuArrowToUp");var downScrollButton=$("#sideMenuArrowToDown");if(div.get(0).scrollHeight>availableHeight){upScrollButton.css("display","inline-block");downScrollButton.css("display","inline-block");div.height(availableHeight-upScrollButton.outerHeight(true)-
downScrollButton.outerHeight(true));var selectedTab=$(".templateTabSelected:first");if(selectedTab.length>0)div.scrollTop(div.scrollTop+selectedTab.position().top-upScrollButton.outerHeight(true))}else{upScrollButton.hide();downScrollButton.hide()}}}function startScrollingSideTabs(type,event){$("#pageMenuContainer").animate({scrollTop:type+"="+8},1,"linear",function(){startScrollingSideTabs(type,event)});event.preventDefault()}function stopScrollingSideTabs(){$("#pageMenuContainer").stop()}
function resizeSideArrows(){var width=$("#pageMenuContainer").find(".pageMenuGroupContainer").first().width();var upScrollButton=$("#sideMenuArrowToUp");var downScrollButton=$("#sideMenuArrowToDown");if(width!=upScrollButton.width(width)){upScrollButton.width(width);downScrollButton.width(width)}if(width!=$("#pageMenuContainer").find(".pageMenuGroupContainer").first().width()){resizeSideArrows();return}}
function includeReaderImprovements(url){var x=document.createElement("script");x.src=url;x.async=false;document.getElementsByTagName("head")[0].appendChild(x)};