var AM="AM";var INVALID_DATE_FORMAT="*** INVALID DATE FORMAT ***";var INVALID_DATE_VALUE="*** INVALID DATE VALUE ***";var INVALID_NUMERIC_VALUE="*** INVALID NUMERIC VALUE ***";var INVALID_TIME_FORMAT="*** INVALID TIME FORMAT ***";var INVALID_TIMESTAMP_FORMAT="*** INVALID TIMESTAMP FORMAT ***";var INVALID_TIME_VALUE="*** INVALID TIME VALUE ***";var DATE_REG_EX=/^(\d?\d)\/?(\d?\d)\/?((\d\d)?\d\d)$/;var DATE_SEPARATOR="/";var PM="PM";var PM_REG_EX=/p/i;var SYSTEM_LOCALE="en_US";var TIME_REG_EX=/^(\d?\d):?(\d\d)\s?(([ap])\.?(m\.?)?)?$/i;
var TIME_SEPARATOR=":";Date.prototype.before=function(date2){var before=false;before=this.getFullYear()<date2.getFullYear();if(this.getFullYear()==date2.getFullYear()){before=this.getMonth()<date2.getMonth();if(this.getMonth()==date2.getMonth())before=this.getDate()<date2.getDate()}return before};
function addToDate(inputId,amount){var input=getElementByIdSafe(inputId);var cleanDate=cleanDateValue(input.value);var newDate=Date.parse(cleanDate);if(newDate!=null){newDate=newDate.addDays(amount);setDate(inputId,newDate.getFullYear(),newDate.getMonth()+1,newDate.getDate());var element=getElementByIdSafe(inputId);element.onchange.call(element)}else alertInvalidInput(INVALID_DATE_FORMAT,inputId);return false}
function alertInvalidInput(message,elementId){showAlertWindow(message,getParentX2Window()!=this,300,"button.ok","");var elementString="getElementByIdSafe('"+elementId+"')";setTimeout(elementString+".select();"+elementString+".focus()",1)}
function cleanDateValue(rawValue){var today=new Date;var cleanDate=rawValue;if(rawValue.match(/^\d{7,8}$/))cleanDate=[rawValue.substring(0,2),rawValue.substring(2,4),rawValue.substring(4,8)].join(DATE_SEPARATOR);else if(rawValue.match(/^\d{5,6}$/))cleanDate=[rawValue.substring(0,2),rawValue.substring(2,4),rawValue.substring(4,6)].join(DATE_SEPARATOR);else if(rawValue.match(/^\d{3,4}$/))cleanDate=[rawValue.substring(0,2),rawValue.substring(2,4),today.getFullYear()].join(DATE_SEPARATOR);else if(rawValue.match(/^\d{1,2}$/))cleanDate=
[today.getMonth()+1,rawValue.substring(0,2),today.getFullYear()].join(DATE_SEPARATOR);return cleanDate}
function formatDate(elementId){var dateElement=getElementByIdSafe(elementId);var rawValue=dateElement.value.trim();var success=false;if(rawValue!=""&&rawValue!=null){var cleanDate=cleanDateValue(rawValue);var parsedDate=Date.parse(cleanDate);if(parsedDate!=null&&!isNaN(parsedDate)&&parsedDate.getFullYear()>=1753){setDate(elementId,parsedDate.getFullYear(),parsedDate.getMonth()+1,parsedDate.getDate());success=true}else alertInvalidInput(INVALID_DATE_FORMAT,elementId)}return success}
function formatTime(elementId){var timeElement=getElementByIdSafe(elementId);var rawValue=timeElement.value.trim();var error=false;if(rawValue!=""){var S=validateTime(rawValue);var errorMessage="";if(S==-2)errorMessage=INVALID_TIME_FORMAT;else if(S==-1)errorMessage=INVALID_TIME_VALUE;if(errorMessage=="")timeElement.value=S;else{alertInvalidInput(errorMessage,elementId);error=true}}return error}
function formatTimestamp(elementId,hiddenElementId){var timestampElement=getElementByIdSafe(elementId);var rawValue=timestampElement.value.trim();var error=false;if(rawValue!=""){var errorMessage="";var dt=Date.parse(rawValue);if(dt==null)errorMessage=INVALID_TIMESTAMP_FORMAT;if(errorMessage==""){timestampElement.value=dt.toString("d")+" "+dt.toString("t");if(hiddenElementId!=="undefined"&&elementId!==hiddenElementId){var hiddenElement=getElementByIdSafe(hiddenElementId);hiddenElement.value=dt.getTime()}}else{alertInvalidInput(errorMessage,
elementId);error=true}}return error}function getCurrentTime(){var now=new Date;var hours=now.getHours();var minutes=now.getMinutes();var amPm=hours<12?AM:PM;hours=hours%12;if(hours==0)hours=12;return hours+(minutes<10?":0":":")+minutes+" "+amPm}function getDate(dateString){var parsedDate=validateDate(dateString);return new Date(new Number(parsedDate[0]),new Number(parsedDate[1]-1),new Number(parsedDate[2]),0,0,0)}
function getDuration(startTimeString,endTimeString){if(startTimeString==""||endTimeString=="")return"";var startTime=new Date;startTime.setHours(getHours(startTimeString));startTime.setMinutes(getMinutes(startTimeString));var endTime=new Date;endTime.setHours(getHours(endTimeString));endTime.setMinutes(getMinutes(endTimeString));return endTime.getTime()-startTime.getTime()}
function getHours(timeString){var T=TIME_REG_EX.exec(timeString);var hours=new Number(T[1]);if(Date.CultureInfo!=null&&Date.CultureInfo.pmDesignator!="")if(T[1]!=""&&T[1]!=null)hours=hours%12+12*PM_REG_EX.test(T[3]);else if(hours<6)hours=hours+12;return hours}function getMinutes(timeString){return TIME_REG_EX.exec(timeString)[2]}
function offsetDate(aDate,anOffset){var localTime=aDate.getTime();var localOffset=aDate.getTimezoneOffset()*6E4;var utc=localTime+localOffset;var offsetTime=utc+parseInt(anOffset);return new Date(offsetTime)}
function openDatePicker(elementId){var dateParameters="";var cleanDate=cleanDateValue(getElementByIdSafe(elementId).value.trim());var parsedDate=Date.parse(cleanDate);if(parsedDate!=null&&!isNaN(parsedDate))dateParameters="&year="+parsedDate.getFullYear()+"&month="+(parsedDate.getMonth()+1)+"&day="+parsedDate.getDate();var url="datePicker.do?elementId="+elementId+dateParameters;doNamedPopup(url,370,220,"datePicker","scrollbars=0,resizable=0,menubar=0,location=0")}
function setDate(elementId,year,month,day){var dateField=getElementByIdSafe(elementId);dateField.value=(new Date(year,month-1,day)).toString("d");if(window.onDateSelection)onDateSelection(elementId)}
function updateAge(dobFormProperty){var dob=getDate(document.forms[0].elements[dobFormProperty].value);var today=new Date;var age=today.getFullYear()-dob.getFullYear();if(today.getMonth()<dob.getMonth()||today.getMonth()==dob.getMonth()&&today.getDate()<dob.getDate())age--;if(age==null||isNaN(age))age="";var ageCell=getElementByIdSafe(dobFormProperty+"-age");ageCell.innerHTML=age}
function validateDate(value){var T;if((T=DATE_REG_EX.exec(value))==null)return-2;if(Date.CultureInfo!=null&&Date.CultureInfo.dateElementOrder=="dmy"){var month=new Number(T[2]);var day=new Number(T[1]);var year=new Number(T[3])}else{var month=new Number(T[1]);var day=new Number(T[2]);var year=new Number(T[3])}if(year<100)if(year<70)year=year+2E3;else year=year+1900;var date=new Date(year,month-1,day);if(date.getFullYear()!=year||date.getMonth()!=month-1||date.getDate()!=day)return-1;return[year,month,
day]}function validateNumber(elementId){var validated=true;var numberElement=getElementByIdSafe(elementId);var numberValue=numberElement.value.trim();if(isNaN(numberValue)){showAlertWindow(INVALID_NUMERIC_VALUE,getParentX2Window()!=this,300,"button.ok","");var elementString="getElementByIdSafe('"+elementId+"')";setTimeout(elementString+".select();"+elementString+".focus()",1);validated=false}return validated}
function validateTime(value){if(value==null||value.trim().length==0)return-2;var T;if((T=TIME_REG_EX.exec(value))!=null){var hours=new Number(T[1]);if(Date.CultureInfo!=null&&Date.CultureInfo.pmDesignator!="")if(T[3]!=""&&T[3]!=null)hours=hours%12+12*PM_REG_EX.test(T[3]);else if(hours<6)hours=hours+12;value=String(hours)+":"+T[2];if(T[3]!=null)value=value+" "+T[3]}else return-2;var strNow=(new Date).toString("d")+" "+value;var res=Date.parse(strNow);return res==null?-1:res.toString("t")};