var DYNAMIC_PICKLIST_POPUP_ID_SUFFIX="-popup";var TIMEOUT_INTERVAL=2E3;var dynamicPickListById=new Array;
function DynamicPickList(id,popupId,actionName,displayProperty,pickListAttributes,authenticationCode,isDetail,isForeignKey,wizardDetailKey,childDetailSetId,childDetailId,disableAutoComplete,disableRelatedUpdate,hasCustomHeader,additionalParams,timeoutValue){var timeoutId=0;var current=0;var options=new Array;var timeoutInterval=TIMEOUT_INTERVAL;var inputField=document.getElementById(id);var popup=document.getElementById(getPopupIdFromPickListId(id));this.additionalParams=additionalParams;this.authenticationCode=
authenticationCode;this.displayProperty=displayProperty;this.hasCustomHeader=hasCustomHeader;this.pickListAttributes=pickListAttributes;this.values=new Array;this.flipped=false;if(timeoutValue)timeoutInterval=timeoutValue;inputField.addEventListener("blur",hidePopup);function DynamicPickList_constructUri(){var dynamicPickList=dynamicPickListById[id];var uri=actionName;var separator="?";if(uri.indexOf("?")==uri.length-1)separator="";else if(uri.indexOf("?")>0)separator="&";var params="value="+encodeParameter(inputField.value);
params+="&update="+dynamicPickList.displayProperty;params+="&"+dynamicPickList.pickListAttributes;params+="&auth="+dynamicPickList.authenticationCode;if(dynamicPickList.additionalParams)params+="&"+dynamicPickList.additionalParams;uri=rewriteUrl(uri);return uri+separator+params}function DynamicPickList_displayList(responseAsString){var dynamicPickList=dynamicPickListById[id];popup.innerHTML=DynamicPickList_formatList(responseAsString);current=0;options=popup.getElementsByTagName("tr");var minLength=
!dynamicPickList.hasCustomHeader?1:2;if(options.length>minLength||options.length==minLength&&disableAutoComplete=="true"){DynamicPickList_setPopupStyles();for(var i=0;i<options.length;i++){options[i].index=i;addOptionHandlers(options[i])}options[0].className="menuItemHighlight";shim(popup.id)}else{var refresh=false;if(dynamicPickList.hasCustomHeader&&disableAutoComplete!="true")customDynamicHeaderRowAutoComplete(dynamicPickList,inputField);if(refresh){window.setTimeout(DynamicPickList_refreshFunction,
timeoutInterval);unShim(popup.id);inputField.focus()}else{if(options.length==minLength)DynamicPickList_updateValue(minLength-1);hidePopup()}}}function DynamicPickList_updateValue(index){var dynamicPickList=dynamicPickListById[id];var valueToUpdate="";if(dynamicPickList.hasCustomHeader)index--;if(dynamicPickList.values.length==0){dynamicPickList.values[index]=inputField.value;if(dynamicPickList.values.length==0)dynamicPickList.values[index]=" "}var components=[""];if(dynamicPickList.values[index]!=
null)components=dynamicPickList.values[index].split("|");if(isForeignKey=="true"){if(components.length>1)valueToUpdate=components[1];var name=inputField.name.split("#")[1];if(!name){var parentElementId=inputField.parentElement.id;if(parentElementId&&parentElementId.indexOf("_display"))name=parentElementId.replace("_display","")}var hiddenInput=document.forms[0].elements[name];if(hiddenInput)hiddenInput.value=valueToUpdate;if(typeof disableRelatedUpdate==="undefined"&&isDetail=="true"||typeof disableRelatedUpdate!=
"undefined"&&!disableRelatedUpdate&&typeof updateRelatedValue==="function")updateRelatedValue(name,id,displayProperty,wizardDetailKey,childDetailSetId,childDetailId)}if(components[0].length>0){inputField.value=components[0];inputField.dynamicChange="true";if(isInternetExplorer())$(inputField).trigger("change");else{var eventObject=document.createEvent("HTMLEvents");eventObject.initEvent("change",true,false);inputField.dispatchEvent(eventObject)}}}function DynamicPickList_formatList(responseAsString){var buffer=
"";var dynamicPickList=dynamicPickListById[id];if(dynamicPickList.hasCustomHeader)buffer+=customDynamicHeaderRow(inputField);var lists=new Array;lists=splitString(responseAsString);if(lists.length>0&&lists[0].length>0){var valuesToShow=new Array;valuesToShow=splitString(lists[0]);buffer+='<table border="0" cellpadding="0" cellspacing="0">';for(var i=0;i<valuesToShow.length;i++){buffer+="<tr>";var valueDisplay=valuesToShow[i].split("|");for(var j=0;j<valueDisplay.length;j++){buffer+='<td  nowrap id="';
buffer+=!dynamicPickList.hasCustomHeader?i:i+1;buffer+='" class="dynamicPickListElement">';if(valueDisplay[j].trim()=="")buffer+="&nbsp;";else buffer+=valueDisplay[j];buffer+="<td>"}buffer+="</tr>"}buffer+="</table>"}if(lists.length>1&&lists[1].length>0)dynamicPickList.values=splitString(lists[1]);return buffer}function DynamicPickList_setPopupStyles(){var maxHeight;var obj=document.getElementById(id);var curleft=findPositionX(obj);var curTop=findPositionY(obj);var grid=document.getElementById("dataGrid");
if(isInternetExplorer()){maxHeight=Math.round(document.body.offsetHeight/3)-20;if(window.name=="wizard"){popup.style.left=curleft-inputField.offsetWidth-50+"px";popup.style.top=curTop-inputField.offsetHeight+"px"}else if(isDetail=="true"||grid==null){popup.style.left=curleft+1+"px";popup.style.top=curTop+inputField.offsetHeight+4+"px"}else{popup.style.left=curleft+2+"px";popup.style.top=curTop+inputField.offsetHeight+2+"px"}}else maxHeight=Math.round(window.outerHeight/3);popup.style.height="";if(popup.offsetHeight<
maxHeight){popup.style.overflow="hidden";popup.style.overflowY="hidden";unShim(popup.id)}else if(isMozillaDerivative()){popup.style.maxHeight=maxHeight+"px";popup.style.overflow="-moz-scrollbars-vertical";popup.style.overflowY="scroll"}else{popup.style.height=maxHeight;popup.style.overflowY="scroll"}if(isSafari()||isChrome()){var maxWidth="";var tables=popup.getElementsByTagName("table");for(var i=0;i<tables.length;i++){var width=tables[i].offsetWidth;if(maxWidth==""||maxWidth<width)maxWidth=width}popup.style.width=
maxWidth+(popup.offsetHeight<maxHeight?0:getScrollbarWidth());for(var i=0;i<tables.length;i++)tables[i].style.width=maxWidth}else{var tables=popup.getElementsByTagName("table");for(var i=0;i<tables.length;i++)tables[i].style.width="100%"}if(isDetail=="false")if(getWindowHeight()<curTop+popup.offsetHeight-getScrollCoordinates()[1]+18){this.savedTop=popup.style.top;this.savedLeft=popup.style.left;this.flipped=true;if(isMozillaDerivative())popup.style.top=curTop-popup.offsetHeight+"px";else{popup.style.left=
curleft+2+"px";popup.style.top=curTop-popup.offsetHeight+inputField.offsetHeight-18+"px"}}else{popup.scrollTop=0;if(this.flipped){this.flipped=false;popup.style.top=this.savedTop;popup.style.left=this.savedLeft}}else popup.scrollTop=0;popup.style.visibility="visible";popup.style.position="absolute"}function DynamicPickList_refreshFunction(){refreshPickList(DynamicPickList_constructUri,DynamicPickList_displayList)}function keyHandler(e){if(timeoutId>0&&e.keyCode!=9){window.clearTimeout(timeoutId);
timeoutId=0}switch(e.keyCode){case 38:if(current>0){options[current].className="";current--;options[current].className="menuItemHighlight";options[current].scrollIntoView(false)}break;case 40:if(current<options.length-1){options[current].className="";current++;options[current].className="menuItemHighlight";options[current].scrollIntoView(false)}break;case 13:case 14:if(popup.style.visibility=="visible"){popup.style.visibility="hidden";DynamicPickList_updateValue(current);unShim(popup.id);inputField.focus();
if(isInternetExplorer())event.returnValue=false;else e.preventDefault()}break;case 27:if(popup.style.visibility=="visible")hidePopup();break;case 46:DynamicPickList_updateValue(current);break;case 36:case 35:case 37:case 39:break;case 9:var dynamicPickList=dynamicPickListById[id];if(dynamicPickList.values.length==0&&inputField.value.length==0&&timeoutId==0)DynamicPickList_updateValue(current);else if(popup.style.visibility=="visible")hidePopup();break;default:timeoutId=window.setTimeout(DynamicPickList_refreshFunction,
timeoutInterval)}}function mouseClickHandler(e){var dynamicPickList=dynamicPickListById[id];var refresh=false;if(dynamicPickList.hasCustomHeader)refresh=customDynamicHeaderRowMouseClick(dynamicPickList,e);if(refresh){window.setTimeout(DynamicPickList_refreshFunction,timeoutInterval);unShim(popup.id);inputField.focus()}else{hidePopup();DynamicPickList_updateValue(current);inputField.focus()}}function mouseOverHandler(e){options[current].className="";if(eventElement(e).id)current=eventElement(e).id;
else current=eventElement(e).index;options[current].className="menuItemHighlight"}function handlePopupOver(){removeListener(inputField,"blur",hidePopup)}function handlePopupOut(){if(popup.style.visibility=="visible"){addListener(inputField,"blur",hidePopup);inputField.focus()}}function hidePopup(){popup.style.visibility="hidden";popup.style.position="absolute";unShim(popup.id)}function addOptionHandlers(option){addListener(option,"click",mouseClickHandler);addListener(option,"mouseover",mouseOverHandler)}
addKeyListener(inputField,keyHandler);addListener(popup,"mouseover",handlePopupOver);addListener(popup,"mouseout",handlePopupOut);dynamicPickListById[id]=this}function refreshPickList(buildUrlFunction,successFunction){makeAsynchronousTextRequest(buildUrlFunction(),successFunction,"doNothing()")}function doNothing(){}var viewFieldContainerId;
function lookupViewFields(elementName,referenceTableOid,schoolOid,viewContainerId){viewFieldContainerId=viewContainerId;var referenceCode=document.forms[0].elements[elementName].value;if(referenceCode!=""){var url="referenceLookup.do?referenceTableOid="+referenceTableOid+"&referenceCode="+referenceCode+"&schoolOid="+schoolOid;makeSynchronousTextRequest(url,"updateViewFieldContainer","clearViewFieldContainer")}else clearViewFieldContainer()}
function updateViewFieldContainer(viewFieldValue){var viewContainer=document.getElementById(viewFieldContainerId);if(viewContainer!=null)viewContainer.innerHTML=viewFieldValue}function clearViewFieldContainer(){updateViewFieldContainer("")}function clearListEditField(displayId,propertyId){document.forms[0].elements[displayId].value="";document.forms[0].elements[propertyId].value=""}function getPopupIdFromPickListId(pickListId){return pickListId+DYNAMIC_PICKLIST_POPUP_ID_SUFFIX}
function splitString(stringToSplit){var SIZE_OF_SIZE=5;var numberOfValues=parseInt(stringToSplit.substr(0,SIZE_OF_SIZE),10);if(isNaN(numberOfValues))return"";var values=new Array(numberOfValues);var startIndex=(numberOfValues+1)*SIZE_OF_SIZE;for(var i=0;i<numberOfValues;i++){var size=parseInt(stringToSplit.substr((i+1)*SIZE_OF_SIZE,SIZE_OF_SIZE),10);values[i]=stringToSplit.substr(startIndex,size);startIndex+=size}return values}
function checkSharedAddressIcon(inputField,sharedIcoId,unsharedIcoId){var content=inputField.value;var sharedIco=document.getElementById(sharedIcoId);var unsharedIco=document.getElementById(unsharedIcoId);if(sharedIco!=null&&unsharedIco!=null)if(inputField.dynamicChange=="true"){sharedIco.style.display="inline";unsharedIco.style.display="none";inputField.dynamicChange=null}else if(sharedIco.style.display=="none")if(content!=null&&content!="")unsharedIco.style.display="inline";else unsharedIco.style.display=
"none"}function eventElement(event){if(isMozillaDerivative())return event.currentTarget;else return event.srcElement}function addKeyListener(element,listener){if(isSafari())element.addEventListener("keydown",listener,false);else if(isMozillaDerivative())element.addEventListener("keydown",listener,false);else element.attachEvent("onkeydown",listener)}
function addListener(element,type,listener){if(element.addEventListener)element.addEventListener(type,listener,false);else element.attachEvent("on"+type,listener)}function removeListener(element,type,listener){if(element.removeEventListener)element.removeEventListener(type,listener,false);else element.detachEvent("on"+type,listener)};