var MINIMUM_GRID_WIDTH=600;var SCROLL_DIRECTION_NEXT="next";var SCROLL_DIRECTION_PREVIOUS="previous";var UNAVAILABLE_WIDTH=123;var totalRecords=0;var selectionCount=0;var runningSelectionElementName="runningSelection";var runningSelectionCountId="runningSelectionCount";var singleSelectionElementName="singleSelection";var scrollDirectionElementName="scrollDirection";
function addToRunningSelection(formName,value){var runningSelection=document.forms[formName].elements[runningSelectionElementName].value;if(!checkDelimitedList(runningSelection,value)){runningSelection=addToDelimitedList(runningSelection,value);document.forms[formName].elements[runningSelectionElementName].value=runningSelection;var selectionCount=document.getElementById(runningSelectionCountId);var count=selectionCount.innerHTML;count++;selectionCount.innerHTML=count}}
function clearPickListSelection(elementName){$("input[name='"+escapeJQuery(elementName)+"']").val("")}function clearRunningSelection(formName,allRowsId,checkboxName){document.forms[formName].elements[runningSelectionElementName].value="";var selectionCount=document.getElementById(runningSelectionCountId);selectionCount.innerHTML=0;var allRowsCheckbox=document.getElementById(allRowsId);if(allRowsCheckbox!=null){allRowsCheckbox.checked=false;selectAllRows(formName,allRowsId,checkboxName,false)}}
function clearSingleSelection(formName){var selectedRadioId=document.forms[formName].elements[singleSelectionElementName].value;document.forms[formName].elements[singleSelectionElementName].value="";var radio=document.getElementById(selectedRadioId);if(radio!=null){radio.checked=false;$(radio.parentNode.parentNode).removeClass("listCellHighlight")}}
function getLastSelectedValue(formName){var lastSelectedValue="";var runningSelectionElement=document.forms[formName].elements[runningSelectionElementName];if(runningSelectionElement!=null){var runningSelection=runningSelectionElement.value;var index=runningSelection.lastIndexOf(",");if(index>-1)lastSelectedValue=runningSelection.substring(index+1,runningSelection.length);else if(runningSelection.length>0)lastSelectedValue=runningSelection}else{var singleSelectionElement=document.forms[formName].elements[singleSelectionElementName];
if(singleSelectionElement!=null)lastSelectedValue=singleSelectionElement.value}return lastSelectedValue}
function preselectRow(formName){var radio=null;var form=document.forms[formName];var element=form.elements[singleSelectionElementName];var scrollDirection=form.elements[scrollDirectionElementName].value;if(scrollDirection==SCROLL_DIRECTION_NEXT)radio=$("input:radio").not(":disabled").first();else if(scrollDirection==SCROLL_DIRECTION_PREVIOUS)radio=$("input:radio").not(":disabled").last();else if(element.value==null||element.value=="")radio=$("input:radio").not(":disabled").first();else radio=$("[id='"+
escapeJQuery(element.value)+"']");if(radio.length>0){radio.prop("checked",true);radio.closest("tr").addClass("listCellHighlight");radio.focus();element.value=radio.val()}form.elements[scrollDirectionElementName].value=""}
function preselectRows(formName,allRowsId,trackLastSelection){if(document.forms[formName]!=null){var checkboxIds=splitStringOnComma(document.forms[formName].elements[runningSelectionElementName].value);for(var i=0;i<checkboxIds.length;i++){var checkbox=getElementByIdSafe(checkboxIds[i]);if(checkbox!=null){checkbox.checked=true;$(checkbox.parentNode.parentNode).addClass("listCellHighlight");selectionCount++;if(selectionCount==totalRecords&&totalRecords>1){var allRowsCheckbox=document.getElementById(allRowsId);
allRowsCheckbox.checked=true}}}if(trackLastSelection)updateLastSelection(formName,true)}}
function removeFromRunningSelection(formName,value){var runningSelection=document.forms[formName].elements[runningSelectionElementName].value;if(checkDelimitedList(runningSelection,value)){runningSelection=removeFromDelimitedList(runningSelection,value);document.forms[formName].elements[runningSelectionElementName].value=runningSelection;var selectionCount=document.getElementById(runningSelectionCountId);var count=selectionCount.innerHTML;count--;selectionCount.innerHTML=count}}
function resizeGrid(gridId){$("[id^="+gridId+"]").each(function(){var grid=this;var SCROLL_BAR_HEIGHT=20;var documentWidth=getWindowWidth();var newGridWidth=documentWidth-UNAVAILABLE_WIDTH;var layoutTabs=$("#layoutVerticalTabs");if($(layoutTabs).length&&$(layoutTabs).width()>0)newGridWidth=documentWidth-$(layoutTabs).width()-30;if(!isInternetExplorer())if($(document).height()>getWindowHeight())newGridWidth=newGridWidth-SCROLL_BAR_HEIGHT;if(isInternetExplorer())newGridWidth-=20;if(newGridWidth>MINIMUM_GRID_WIDTH)$(grid).css("width",
newGridWidth);if(isInternetExplorer()||isFirefox()){var newHeight=grid.offsetHeight;if(grid.scrollWidth+2>grid.offsetWidth&&grid.scrollHeight+2==grid.offsetHeight)$(grid).css("height",grid.offsetHeight+SCROLL_BAR_HEIGHT);if(grid.scrollWidth+2==grid.offsetWidth&&grid.scrollHeight+2+SCROLL_BAR_HEIGHT==grid.offsetHeight)$(grid).css("height",grid.offsetHeight-SCROLL_BAR_HEIGHT)}})}
function selectAllRows(formName,allRowsId,checkboxName,trackLastSelection,ignoreSelectionCount){var allRowsCheckbox=document.getElementById(allRowsId);var isChecked=false;selectionCount=0;if(allRowsCheckbox.checked){isChecked=true;selectionCount=totalRecords}var checkboxArray=document.forms[formName].elements[checkboxName];for(var i=0;i<checkboxArray.length;i++){var checkbox=checkboxArray[i];checkbox.checked=isChecked;if(isChecked)$(checkbox.parentNode.parentNode).addClass("listCellHighlight");else{$(checkbox.parentNode.parentNode).removeClass("listCellHighlight");
$(checkbox.parentNode.parentNode).removeClass("listCellLastSelectionHighlight")}if(ignoreSelectionCount!=true)if(isChecked)addToRunningSelection(formName,checkbox.value);else removeFromRunningSelection(formName,checkbox.value)}if(trackLastSelection)updateLastSelection(formName,true)}
function selectMultipleRow(formName,allRowsId,checkboxId,trackLastSelection,ignoreSelectionCount){if(checkboxId!=null&&checkboxId.indexOf("'")!=-1)checkboxId=checkboxId.replace("'","\\'");var checkbox=$("input[id='"+checkboxId+"']")[0];if(checkbox!=null)if(checkbox.checked){var highlightClass="listCellHighlight";if(trackLastSelection){highlightClass="listCellLastSelectionHighlight";updateLastSelection(formName,false)}$(checkbox.parentNode.parentNode).addClass(highlightClass);selectionCount++;if(selectionCount==
totalRecords&&totalRecords>1){var allRowsCheckbox=getElementByIdSafe(allRowsId);allRowsCheckbox.checked=true}if(ignoreSelectionCount!=true)addToRunningSelection(formName,checkbox.value)}else{$(checkbox.parentNode.parentNode).removeClass("listCellHighlight");$(checkbox.parentNode.parentNode).removeClass("listCellLastSelectionHighlight");selectionCount--;if(totalRecords>1){var allRowsCheckbox=getElementByIdSafe(allRowsId);allRowsCheckbox.checked=false}if(ignoreSelectionCount!=true)removeFromRunningSelection(formName,
checkbox.value);var lastSelection=getLastSelectedValue(formName);if(lastSelection!=""){var lastCheckbox=getElementByIdSafe(lastSelection);if(lastCheckbox!=null)$(lastCheckbox.parentNode.parentNode).addClass("listCellHighlight")}if(trackLastSelection)updateLastSelection(formName,true)}}
function selectSingleRow(formName,radioName,value){document.forms[formName].elements[singleSelectionElementName].value=value;var radios=$("input:radio[name='"+radioName+"']");radios.filter(":checked").closest("tr").addClass("listCellHighlight").removeClass("listCell");radios.not(":checked").closest("tr").removeClass("listCellHighlight").addClass("listCell")}
function selectAdjacentSingleRow(form,radioName,direction,nextPageEvent,previousPageEvent){var radioArray=forceElementToArray(form.elements[radioName]);for(var i=0;i<radioArray.length;i++){var radio=radioArray[i];var newRadio=null;if(radio.checked){if(direction==SCROLL_DIRECTION_PREVIOUS)if(i>0)newRadio=radioArray[i-1];else{if(!form.elements["prevPageButton"].disabled){form.elements[scrollDirectionElementName].value=SCROLL_DIRECTION_PREVIOUS;doSubmit(previousPageEvent,form)}}else if(direction==SCROLL_DIRECTION_NEXT)if(i<
radioArray.length-1)newRadio=radioArray[i+1];else if(!form.elements["nextPageButton"].disabled){form.elements[scrollDirectionElementName].value=SCROLL_DIRECTION_NEXT;doSubmit(nextPageEvent,form)}break}}if(newRadio!=null){radio.checked=false;$(radio.parentNode.parentNode).removeClass("listCellLastSelectionHighlight");$(radio.parentNode.parentNode).removeClass("listCellHighlight");newRadio.checked=true;$(newRadio.parentNode.parentNode).addClass("listCellHighlight");newRadio.focus();form.elements[singleSelectionElementName].value=
newRadio.value}}function setWidthConstraintsForPopup(){UNAVAILABLE_WIDTH=30;MINIMUM_GRID_WIDTH=100}function setWidthConstraintsForWizard(){UNAVAILABLE_WIDTH=175;MINIMUM_GRID_WIDTH=100}function splitStringOnComma(str){var str1=str.replace(/, /g,",");return str1.split(",")}
function updateLastSelection(formName,highlight){var lastSelection=getLastSelectedValue(formName);if(lastSelection!=""){var lastCheckbox=getElementByIdSafe(lastSelection);if(lastCheckbox!=null)if(highlight){$(lastCheckbox.parentNode.parentNode).removeClass("listCellHighlight");$(lastCheckbox.parentNode.parentNode).addClass("listCellLastSelectionHighlight")}else{$(lastCheckbox.parentNode.parentNode).removeClass("listCellLastSelectionHighlight");$(lastCheckbox.parentNode.parentNode).addClass("listCellHighlight")}}}
;