jQuery.attrFn=jQuery.attrFn||{};jQuery.curCSS=jQuery.css;var _ajax=$.ajax;
$.ajax=function(options){if(options.type&&options.type.toUpperCase()!="GET"&&options.type.toUpperCase()!="OPTIONS"&&options.type.toUpperCase()!="HEAD"){if(!options.data)options.data={};var token=$('input[name^="org\\.apache\\.struts\\.taglib\\.html\\.TOKEN"]').val();if(typeof options.data=="string"){if(options.data!="")options.data+="&";options.data+="org.apache.struts.taglib.html.TOKEN="+token}else options.data["org.apache.struts.taglib.html.TOKEN"]=token}options.cache=true;return _ajax(options)};
var _parseJSON=$.parseJSON;$.parseJSON=function(str){if(!str)return null;return _parseJSON(str)};
(function(){var matched,browser;jQuery.uaMatch=function(ua){ua=ua.toLowerCase();var match=/(chrome)[ \/]([\w.]+)/.exec(ua)||/(webkit)[ \/]([\w.]+)/.exec(ua)||/(opera)(?:.*version|)[ \/]([\w.]+)/.exec(ua)||/(msie) ([\w.]+)/.exec(ua)||ua.indexOf("compatible")<0&&/(mozilla)(?:.*? rv:([\w.]+)|)/.exec(ua)||[];return{browser:match[1]||"",version:match[2]||"0"}};matched=jQuery.uaMatch(navigator.userAgent);browser={};if(matched.browser){browser[matched.browser]=true;browser.version=matched.version}if(browser.chrome)browser.webkit=
true;else if(browser.webkit)browser.safari=true;jQuery.browser=browser})(jQuery);jQuery.fn.compare=function(array){var isEqual=true;if(this.length!=array.length)isEqual=false;if(isEqual){var a=this.sort();var b=array.sort();for(var i=0;array[i];i++)if(a[i]!=b[i]){isEqual=false;break}}return isEqual};
jQuery.fn.createCollapsible=function(){var DEFAULT_DEFAULT_OPEN=true;var DEFAULT_PERSIST=true;var params=arguments.length<1?null:arguments[0];var default_open=params==null||params.default_open==undefined?DEFAULT_DEFAULT_OPEN:params.default_open;var persist=params==null||params.persist==undefined?DEFAULT_PERSIST:params.persist;var elements=params==null||params.elements==undefined?null:params.elements;var action=params==null||params.action==undefined?function(new_state_open,elems,collapsible){elems.toggle()}:
params.action;var onClickFunc=function(){var elems;if(elements instanceof Function)elems=elements.call(this,$(this));else if(typeof elements=="string")elems=$(elements);else elems=$(this).children();var current_state_open=jQuery.data(this,"open");current_state_open=current_state_open==undefined?default_open:current_state_open;var new_state_open=jQuery.data(this,"open",!current_state_open);action.call(document,new_state_open,elems,$(this))};if(persist)$(this).on("click",onClickFunc);else $(this).click(onClickFunc);
return this};jQuery.fn.makeLink=function(href){return $(this).hover(function(){$(this).css({"cursor":"pointer"})}).click(function(evt){evt=evt?evt:event?event:null;if(evt){var elem=evt.target?evt.target:evt.srcElement?evt.srcElement:null;if(elem){if(elem.nodeName!="a"&&elem.nodeName!="A")window.location.href=href}else window.location.href=href}else window.location.href=href})};
jQuery.fn.search=function(elementSelector){var searcher=$(this);var params=arguments.length>1?arguments[1]:{};var onMatch=params.onmatch!=undefined?params.onmatch:function(e){e.show()};var onNoMatch=params.onnomatch!=undefined?params.onnomatch:function(e){e.hide()};var filter=params.filter!=undefined?params.filter:function(){return false};var begin=params.begin!=undefined?params.begin:function(){};var finish=params.finish!=undefined?params.finish:function(){};var select=params.select!=undefined?params.select:
function(e){return e.text()};searcher.on("keyup",function(){begin.call(this);var elements=$(elementSelector);var input=$(this);var searchVal=input.val().toLowerCase();jQuery.each(elements,function(i,e){if(!filter.call(this,$(e))){var selectVal=select.call(this,$(e)).toLowerCase();if(searchVal==undefined||searchVal.length==0||selectVal.indexOf(searchVal)>=0)onMatch.call(this,$(e));else onNoMatch.call(this,$(e))}});finish.call(this)});return this};
jQuery.fn.sort=function(){return this.pushStack([].sort.apply(this,arguments),[])};jQuery.fn.serializeFormJSON=function(){var o={};var a=this.serializeArray();$.each(a,function(){if(o[this.name]){if(!o[this.name].push)o[this.name]=[o[this.name]];o[this.name].push(this.value||"")}else o[this.name]=this.value||""});return o};