var DELAY_MILLISECONDS=500;var ERROR_SPAN_ID_PREFIX="err";var IFRAME_SPAN_ID="content";var MENU_BACKGROUND_CSS_CLASS="spellCheckBackground";var MENU_SELECTED_ROW_CSS_CLASS="menuItemHighlight";var SPELLING_MENU_ID="spellingMenu";var SUGGESTION_ID_PREFIX="sugg";var MAX_SUGGESTIONS=8;var MENU_TIMEOUT_INTERVAL=600;var WORD_CLOSE_BOUNDARIES=new Array(" ","","<","/","-",",",".",":",";",")","]",'"',"'","!","?","&");
var WORD_OPEN_BOUNDARIES=new Array(" ","",">","/","-",",",".",":",";","(","[",'"',"'","!","?","&");var displayCheckButton=false;var highlightedMenuRow=null;var menuTimeoutId=0;var scFields=new Array;var hasMisspelling=false;function checkSpelling(){for(id in scFields)makeSpellCheckRequest(id)}function customCheckSpelling(){for(id in scFields)makeCustomSpellCheckRequest(id);if(!hasMisspelling)alert(grabResource("message.spellCheck.noMisspellings"));hasMisspelling=false}
function closeMenu(){var suggestionMenu=document.getElementById(SPELLING_MENU_ID);suggestionMenu.style.visibility="hidden"}function delay(){var startTime=new Date;var currentTime=null;do currentTime=new Date;while(currentTime-startTime<DELAY_MILLISECONDS)}function handleFailureReply(){alert(grabResource("message.spellCheck.unableToProcess",true))}
function handleSuccessReply(replyXml){if(replyXml!=null){var root=replyXml.getElementsByTagName("r")[0];if(root!=null){var scFieldId=root.getAttribute("id");var scField=scFields[scFieldId];scField.reset();var errors=root.getElementsByTagName("e");if(errors.length>0){for(var i=0;i<errors.length;i++){var errorWord=errors[i].getAttribute("w");var suggestionList=new Array;var suggestions=errors[i].getElementsByTagName("s");if(suggestions.length>0)for(var j=0;j<suggestions.length;j++)suggestionList[j]=
suggestions[j].getAttribute("w");scField.identifySpelling(errorWord,suggestionList)}scField.enableSuggestions()}else alert(grabResource("message.spellCheck.noMisspellings"));if(isInternetExplorer())scField.prepareHandlers()}}else alert(grabResource("message.spellCheck.noMisspellings"))}
function handleCustomSuccessReply(replyXml){if(replyXml!=null){var root=replyXml.getElementsByTagName("r")[0];if(root!=null){var scFieldId=root.getAttribute("id");var scField=scFields[scFieldId];scField.reset();var errors=root.getElementsByTagName("e");if(errors.length>0){for(var i=0;i<errors.length;i++){var errorWord=errors[i].getAttribute("w");var suggestionList=new Array;var suggestions=errors[i].getElementsByTagName("s");if(suggestions.length>0)for(var j=0;j<suggestions.length;j++)suggestionList[j]=
suggestions[j].getAttribute("w");scField.identifySpelling(errorWord,suggestionList)}scField.enableSuggestions();hasMisspelling=true}if(isInternetExplorer())scField.prepareHandlers()}}}
function highlightMenuOption(optionNumber){stopMenuCountdown();if(highlightedMenuRow!=null)highlightedMenuRow.className=MENU_BACKGROUND_CSS_CLASS;var id=SUGGESTION_ID_PREFIX+optionNumber;var td=document.getElementById(id);var menuRow=td.parentNode;menuRow.className=MENU_SELECTED_ROW_CSS_CLASS;highlightedMenuRow=menuRow}function isPositionKey(keyCode){return keyCode>=35&&keyCode<=40}
function makeDictionaryAddRequest(id,word){makeSynchronousXmlRequest("spellCheck.do","void","handleErrorReply","add",word);makeSpellCheckRequest(id)}function makeSpellCheckRequest(id){var scField=scFields[id];var url="spellCheck.do?id="+id;makeAsynchronousXmlRequest(url,"handleSuccessReply","handleErrorReply","text",scField.getTextOnlyContent())}
function makeCustomSpellCheckRequest(id){var scField=scFields[id];var url="spellCheck.do?id="+id;makeSynchronousXmlRequest(url,"handleCustomSuccessReply","handleErrorReply","text",scField.getTextOnlyContent())}function populateForm(){for(id in scFields){var scField=scFields[id];scField.populateFormField()}}
function resizeFrames(){for(id in scFields){scField=scFields[id];if(!scField.singleRow){var iframe=document.getElementById(id);iframe.style.width="0px"}}for(id in scFields){scField=scFields[id];scField.calculateFrameWidth()}for(id in scFields){scField=scFields[id];scField.resizeFrame()}}
function selectMenuOption(scFieldId,errorNumber,optionNumber){var scField=scFields[scFieldId];var errorSpan=scField.fieldDocument.getElementById(ERROR_SPAN_ID_PREFIX+errorNumber);var id=SUGGESTION_ID_PREFIX+optionNumber;var handlerToRemove=scField.handlers[errorNumber];if(errorSpan.removeEventListener)errorSpan.removeEventListener("mouseover",handlerToRemove,false);else if(errorSpan.detachEvent)errorSpan.detachEvent("onmouseover",handlerToRemove);else errorSpan.onmouseover=function(){return false};
errorSpan.style.backgroundColor="";if(optionNumber==1E3)makeDictionaryAddRequest(scFieldId,errorSpan.innerHTML);else{var td=document.getElementById(id);errorSpan.innerHTML=td.innerHTML;scField.truncate()}}function showSuggestions(scFieldId,word,errorNumber){delay();var scField=scFields[scFieldId];scField.showSuggestions(word,errorNumber)}function startMenuCountdown(){stopMenuCountdown();menuTimeoutId=window.setTimeout("closeMenu()",MENU_TIMEOUT_INTERVAL)}
function stopMenuCountdown(){if(menuTimeoutId>0){window.clearTimeout(menuTimeoutId);menuTimeoutId=0}}
function SpellCheckField(id,text,singleRow,maxLength,formProperty,displayCheckButton){var iframe=document.getElementById(id);this.fieldDocument=iframe.contentWindow.document;if(isInternetExplorer()){text=text.replace(/^ /img,"&nbsp;");text=text.replace(/\r?\n/img,"<br>");text=text.replace(/$\s{2}/img,"<br>")}else text=text.replace(/$\s/img,"<br>");text=text.replace(/  /img," &nbsp;");this.displayCheckButton=displayCheckButton;this.errorCount=0;this.errorMaxLength=grabResource("message.truncate.error");
this.limitMaxLength=grabResource("message.truncate.limit");this.warningMaxLength=grabResource("message.truncate.warning");this.formProperty=formProperty;this.handlers=new Array;this.lastWordIndex=0;this.maxLength=maxLength;this.scFieldId=id;this.singleRow=singleRow;this.suggestions=new Array;this.text=text;this.timeoutId=0;this.format(iframe);this.fieldDocument.designMode="on";this.writeContent(this.text);this.prepareHandlers();scFields[id]=this}SpellCheckField.prototype.calculateFrameWidth=SpellCheckField_calculateFrameWidth;
function SpellCheckField_calculateFrameWidth(){if(!this.singleRow){var iframe=parent.document.getElementById(this.scFieldId);this.frameWidth=iframe.offsetParent.offsetWidth;if(isMozillaDerivative())this.frameWidth-=5}}SpellCheckField.prototype.enableSuggestions=SpellCheckField_enableSuggestions;
function SpellCheckField_enableSuggestions(){var errorNumber=0;for(var i=0;i<this.handlers.length;i++){var errorSpan=this.fieldDocument.getElementById(ERROR_SPAN_ID_PREFIX+errorNumber);var scFieldId=this.scFieldId;var suggestions=this.suggestions;if(errorSpan.addEventListener)errorSpan.addEventListener("mouseover",this.handlers[i],false);else if(errorSpan.attachEvent)errorSpan.attachEvent("onmouseover",this.handlers[i]);else errorSpan.onmouseover=this.handlers[i];errorNumber++}}
SpellCheckField.prototype.getCleanContent=SpellCheckField_getCleanContent;
function SpellCheckField_getCleanContent(){var content=this.getRawContent();content=content.replace(/<\!--[\s\S]+?--\>/ig,"");content=content.replace(/\u2018/g,"'");content=content.replace(/\u2019/g,"'");content=content.replace(/\u201c/g,'"');content=content.replace(/\u201d/g,'"');content=content.replace(/\u2013/g,"-");content=content.replace(/\u2014/g,"--");content=content.replace(/<SPAN.+?>/ig,"");content=content.replace(/<\/SPAN>/ig,"");content=content.replace(/<FONT.+?>/ig,"");content=content.replace(/<\/FONT>/ig,
"");if(this.singleRow){content=content.replace(/<p>/ig,"");content=content.replace(/<\/p>/ig,"");content=content.replace(/<br>/ig,"")}else content=content.replace(/<div><br><\/div>/ig,"<div></div>");return content}SpellCheckField.prototype.getRawContent=SpellCheckField_getRawContent;function SpellCheckField_getRawContent(){return this.fieldDocument.body.innerHTML}SpellCheckField.prototype.getTextOnlyContent=SpellCheckField_getTextOnlyContent;
function SpellCheckField_getTextOnlyContent(){var content=this.getRawContent();content=content.replace(/<\!--[\s\S]+?--\>/ig,"");content=content.replace(/\u2018/g,"'");content=content.replace(/\u2019/g,"'");content=content.replace(/\u201c/g,'"');content=content.replace(/\u201d/g,'"');content=content.replace(/\u2013/g,"-");content=content.replace(/\u2014/g,"--");content=content.replace(/<p>/ig,"");content=content.replace(/<\/p>/ig," ");content=content.replace(/<br>/ig," ");content=content.replace(/<.+?>/ig,
"");content=content.replace(/&nbsp;/ig," ");return content}SpellCheckField.prototype.identifySpelling=SpellCheckField_identifySpelling;
function SpellCheckField_identifySpelling(word,suggestions){var spanId=ERROR_SPAN_ID_PREFIX+this.errorCount;var scFieldId=this.scFieldId;var errorNumber=this.errorCount;var content=this.getRawContent();var indexArray=this.findWordPosition(word,content);var wordIndex=indexArray[0];if(wordIndex!=-1){this.handlers[this.errorCount]=function(){parent.showSuggestions(scFieldId,word,errorNumber)};var prefix=indexArray[1];var suffix=indexArray[2];var spanTagOpen=prefix+'<span id="'+spanId+'" style="background-color: yellow;">';
var spanTagClose="</span>"+suffix;var part1=content.substring(0,wordIndex);var part2=content.substring(wordIndex+word.length+prefix.length+suffix.length);var newContent=part1+spanTagOpen+word+spanTagClose+part2;this.writeContent(newContent);if(suggestions.length>0)for(var i=0;i<suggestions.length;i++)this.addSuggestion(word,suggestions[i]);this.errorCount++}}SpellCheckField.prototype.isReady=SpellCheckField_isReady;function SpellCheckField_isReady(){return this.fieldDocument.body!=null}
SpellCheckField.prototype.populateFormField=SpellCheckField_populateFormField;
function SpellCheckField_populateFormField(){var formField=document.forms[0].elements[this.formProperty];if(formField!=null){var valueToSet=this.getCleanContent();if(isInternetExplorer())valueToSet=valueToSet.replace(/(<\/p>)\r\n/img,"$1");valueToSet=valueToSet.replace(/$\s/mg," ");valueToSet=valueToSet.replace(/<style>.+?<\/style>/ig,"");valueToSet=valueToSet.replace(/<\!--[\s\S]+?--\>/ig,"");valueToSet=valueToSet.replace(/<p>/ig,"");valueToSet=valueToSet.replace(/<\/p>/ig,"\n");valueToSet=valueToSet.replace(/<br>/ig,
"\n");valueToSet=valueToSet.replace(/<\/div>/ig,"\n");valueToSet=valueToSet.replace(/<.+?>/ig,"");valueToSet=valueToSet.replace(/&nbsp;/ig," ");valueToSet=valueToSet.replace(/&amp;/ig,"&");valueToSet=valueToSet.replace(/&lt;/ig,"<");valueToSet=valueToSet.replace(/&gt;/ig,">");valueToSet=valueToSet.replace(/&quot;/ig,'"');formField.value=valueToSet.trim()}}SpellCheckField.prototype.resizeFrame=SpellCheckField_resizeFrame;
function SpellCheckField_resizeFrame(){if(!this.singleRow){var iframe=parent.document.getElementById(this.scFieldId);iframe.style.width=this.frameWidth}if(this.displayCheckButton)this.addCheckButton()}SpellCheckField.prototype.showSuggestions=SpellCheckField_showSuggestions;
function SpellCheckField_showSuggestions(word,errorNumber){var suggestionsForWord=this.suggestions[word];var entryCount=0;var tdPadding="padding: 1px 12px 1px 7px;";var menuMarkup='<table id="suggestionTable" border="0" cellspacing="0" cellpadding="0">';if(suggestionsForWord!=null)for(var i=0;i<suggestionsForWord.length;i++){if(i==MAX_SUGGESTIONS)break;menuMarkup+='<tr><td style="'+tdPadding+' font-weight: bold;" id="'+SUGGESTION_ID_PREFIX+i+'" onclick="selectMenuOption(\''+this.scFieldId+"',"+errorNumber+
","+i+')" onmouseover="highlightMenuOption('+i+')">'+suggestionsForWord[i]+"</td></tr>";entryCount++}else{menuMarkup+='<tr><td style="'+tdPadding+' font-style: italic;">'+grabResource("message.spellCheck.noSuggestions",true)+"</td></tr>";entryCount=1}menuMarkup+='<tr><td style="border-top: solid black 1px; '+tdPadding+'" id="'+SUGGESTION_ID_PREFIX+'1000" onclick="selectMenuOption(\''+this.scFieldId+"',"+errorNumber+', 1000)" onmouseover="highlightMenuOption(1000)">'+grabResource("message.spellCheck.addToDictionary",
true)+"</td></tr>";entryCount++;menuMarkup+="</table>";this.renderMenu(menuMarkup,errorNumber,entryCount)}SpellCheckField.prototype.truncate=SpellCheckField_truncate;function SpellCheckField_truncate(){var content=this.getTextOnlyContent();if(this.maxLength!=0&&content.length>this.maxLength){var showConfirm=arguments.length>0?arguments[0]:false;if(!showConfirm||confirm(this.warningMaxLength)){alert(this.errorMaxLength);content=content.substring(0,this.maxLength);this.writeContent(content)}}}
SpellCheckField.prototype.addCheckButton=SpellCheckField_addCheckButton;
function SpellCheckField_addCheckButton(){var iframe=parent.document.getElementById(this.scFieldId);var imageId="img"+this.scFieldId;var image=parent.document.getElementById(imageId);if(image==null){var image=parent.document.createElement("IMG");image.id=imageId;image.src="images/abc.gif";image.border=0;image.style.position="absolute";image.style.zIndex="900";image.title="Check spelling";var fieldId=this.scFieldId;image.onclick=function(){makeSpellCheckRequest(fieldId)};parent.document.body.appendChild(image)}var left=
findPositionX(iframe)+iframe.offsetWidth;var top=findPositionY(iframe);if(isInternetExplorer()){top+=4;left-=20}else{top+=1;left-=21}image.style.left=left;image.style.top=top}SpellCheckField.prototype.addSuggestion=SpellCheckField_addSuggestion;
function SpellCheckField_addSuggestion(word,suggestion){var suggestionsForWord=this.suggestions[word];if(suggestionsForWord==null){suggestionsForWord=new Array;this.suggestions[word]=suggestionsForWord}var containsSuggestion=false;for(var i=0;i<suggestionsForWord.length;i++)if(suggestionsForWord[i]==suggestion){containsSuggestion=true;break}if(!containsSuggestion)suggestionsForWord[suggestionsForWord.length]=suggestion}SpellCheckField.prototype.findWordPosition=SpellCheckField_findWordPosition;
function SpellCheckField_findWordPosition(word,content){var minWordIndex=-1;var prefix="";var suffix="";if(this.lastWordIndex==0&&content.substring(0,word.length)==word)minWordIndex=0;else{var searchStart=0;var spanClosePos=content.toUpperCase().indexOf("</SPAN>",this.lastWordIndex);if(spanClosePos!=-1)searchStart=spanClosePos+7;for(var i=0;i<WORD_OPEN_BOUNDARIES.length;i++)for(var j=0;j<WORD_CLOSE_BOUNDARIES.length;j++){var currentPrefix=WORD_OPEN_BOUNDARIES[i];var currentSuffix=WORD_CLOSE_BOUNDARIES[j];
if(currentPrefix!=""){var searchValue=currentPrefix+word+currentSuffix;var wordIndex=content.indexOf(searchValue,searchStart);if(currentSuffix=="")wordIndex=content.lastIndexOf(searchValue);var searchContent=content.length-searchValue.length;var validSuffix=currentSuffix!=""||wordIndex==searchContent;if(wordIndex!=-1&&(minWordIndex==-1||wordIndex<minWordIndex)&&validSuffix){minWordIndex=wordIndex;prefix=currentPrefix;suffix=currentSuffix}}}}if(minWordIndex!=-1)this.lastWordIndex=minWordIndex;return new Array(minWordIndex,
prefix,suffix)}SpellCheckField.prototype.format=SpellCheckField_format;
function SpellCheckField_format(iframe){if(this.isReady()){this.fieldDocument.body.style.fontFamily="Arial";if(this.singleRow){this.fieldDocument.body.style.whiteSpace="nowrap";if(!isInternetExplorer()){iframe.contentWindow.scrollbars.visible=true;this.fieldDocument.body.style.fontSize="x-small"}else{this.fieldDocument.body.style.fontSize="xx-small";iframe.style.height=17+"px"}}else this.fieldDocument.body.style.fontSize="10pt";iframe.style.border="solid #7f9db9 1px"}}
SpellCheckField.prototype.prepareHandlers=SpellCheckField_prepareHandlers;
function SpellCheckField_prepareHandlers(){if(this.isReady()){var scFieldId=this.scFieldId;var truncateCloseMenu=function(theEvent){var scField=scFields[scFieldId];scField.truncate(true);parent.closeMenu};var pasteHandler=function(theEvent){var showConfirm=true;var scField=scFields[scFieldId];if(theEvent.type=="paste"||theEvent.type=="input")showConfirm=false;var callTruncate=function(){scField.truncate(showConfirm)};setTimeout(callTruncate,100)};this.fieldDocument.execCommand("defaultParagraphSeparator",
false,"div");this.fieldDocument.body.addEventListener("keydown",function(e){handler_wrapLineWithDivOnEnter(e,scFieldId)},false);if(this.fieldDocument.addEventListener){this.fieldDocument.addEventListener("click",truncateCloseMenu,false);if(this.singleRow){this.fieldDocument.addEventListener("keydown",function(e){handler_mozillaSingleLineKeyDown(e,scFieldId)},false);this.fieldDocument.addEventListener("keyup",function(e){handler_mozillaSingleLineKeyUp(e,scFieldId)},false)}else{this.fieldDocument.addEventListener("keypress",
function(e){handler_mozillaMultiLineKeyDown(e,scFieldId)},false);this.fieldDocument.addEventListener("keydown",function(e){handler_mozillaMultiLineKeyDown(e,scFieldId)},false);this.fieldDocument.addEventListener("keyup",function(e){handler_mozillaMultiLineKeyUp(e,scFieldId)},false);this.fieldDocument.body.addEventListener("paste",pasteHandler,false)}}else if(this.fieldDocument.attachEvent){this.fieldDocument.attachEvent("onclick",truncateCloseMenu);this.fieldDocument.attachEvent("onkeydown",parent.closeMenu);
var keyPressHandler=function(theEvent){var scField=scFields[scFieldId];limitText(theEvent,scField,scField.maxLength)};this.fieldDocument.attachEvent("onkeypress",keyPressHandler);this.fieldDocument.attachEvent("onkeyup",keyPressHandler);this.fieldDocument.body.attachEvent("onpaste",pasteHandler)}else{this.fieldDocument.onclick=truncateCloseMenu;this.fieldDocument.onkeydown=parent.closeMenu;if(this.singleRow)this.fieldDocument.onkeypress=handler_nonMozillaSingleLineKeyPress;else this.fieldDocument.onkeypress=
function(e){handler_mozillaMultiLineKeyDown(e,scFieldId)}}parent.document.onclick=closeMenu}}SpellCheckField.prototype.renderMenu=SpellCheckField_renderMenu;
function SpellCheckField_renderMenu(markup,errorNumber,entryCount){parent.stopMenuCountdown();var suggestionMenu=parent.document.getElementById(SPELLING_MENU_ID);suggestionMenu.innerHTML=markup;var errorSpan=this.fieldDocument.getElementById(ERROR_SPAN_ID_PREFIX+errorNumber);var iframe=parent.document.getElementById(this.scFieldId);var posX=findPositionX(iframe)+findPositionX(errorSpan)+4;var posY=findPositionY(iframe)+findPositionY(errorSpan)-this.fieldDocument.body.scrollTop+20;var suggestionTable=
document.getElementById("suggestionTable");height=suggestionTable.offsetHeight;suggestionMenu.style.left=posX+"px";suggestionMenu.style.top=posY+"px";suggestionMenu.style.height=height+"px";if(isInternetExplorer())suggestionMenu.style.width="auto";suggestionMenu.style.visibility="visible";suggestionMenu.onmouseout=startMenuCountdown}SpellCheckField.prototype.reset=SpellCheckField_reset;
function SpellCheckField_reset(){this.errorCount=0;this.suggestions=new Array;this.handlers=new Array;this.lastWordIndex=0;this.writeContent(this.getCleanContent())}SpellCheckField.prototype.writeContent=SpellCheckField_writeContent;
function SpellCheckField_writeContent(content){if(this.isReady()){if(!(isInternetExplorer()||isFirefox())&&content.length==0)content=" ";this.fieldDocument.body.innerHTML=content;if(isFirefox()){this.fieldDocument.execCommand("inserthtml",false,"-");this.fieldDocument.execCommand("undo",false,null)}}}
function handler_mozillaSingleLineKeyDown(theEvent,scFieldId){var scField=scFields[scFieldId];var keyCode=theEvent.keyCode;if(keyCode==13)scField.fieldDocument.designMode="off";else if(theEvent.ctrlKey&&String.fromCharCode(keyCode).toUpperCase()=="A");else if(keyCode==16||keyCode==17);else if(isPositionKey(keyCode)||keyCode==8);else if(!theEvent.shiftKey&&theEvent.keyCode==9)scField.fieldDocument.designMode="off";else{var content=scField.getTextOnlyContent();var maxLength=scField.maxLength;if(maxLength>
0&&content.length>=maxLength)scField.fieldDocument.designMode="off"}return limitText(theEvent,scField,scField.maxLength)}function handler_mozillaSingleLineKeyUp(theEvent,scFieldId){var scField=scFields[scFieldId];var keyCode=theEvent.keyCode;if(theEvent.ctrlKey&&String.fromCharCode(keyCode).toUpperCase()=="A");else if(keyCode==16||keyCode==17);else if(scField.fieldDocument.designMode=="off")scField.fieldDocument.designMode="on";return limitText(theEvent,scField,scField.maxLength)}
function handler_mozillaMultiLineKeyDown(theEvent,scFieldId){var scField=scFields[scFieldId];if(!isSafari()){var keyCode=theEvent.keyCode;if(!theEvent.shiftKey&&theEvent.keyCode==9)scField.fieldDocument.designMode="off"}return limitText(theEvent,scField,scField.maxLength)}
function handler_mozillaMultiLineKeyUp(theEvent,scFieldId){var scField=scFields[scFieldId];var keyCode=theEvent.keyCode;if(scField.fieldDocument.designMode=="off")scField.fieldDocument.designMode="on";return limitText(theEvent,scField,scField.maxLength)}function handler_wrapLineWithDivOnEnter(theEvent,scFieldId){var scField=scFields[scFieldId];if(theEvent.key=="Enter")scField.fieldDocument.execCommand("formatBlock",false,"div")};